import React, { createContext, useContext, useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en-IN', name: 'English', native: 'English', flag: '🇮🇳' },
  { code: 'hi-IN', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr-IN', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'ta-IN', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te-IN', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn-IN', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

export const DICTIONARY = {
  'en-IN': {
    // Top Bar
    brand_title: 'SCHEME GUARD',
    brand_tag: 'MoSPI e-SAKSHI Layer',
    brand_sub: 'Ministry of Statistics & Programme Implementation • Govt. of India',
    search_placeholder: 'Search project ID, district, contractor, cartel...',
    role_admin: 'MoSPI Admin',
    role_district: 'District Officer',
    role_citizen: 'Citizen Portal',
    role_persona: 'Active Authority Persona',
    role_admin_sub: 'National oversight & cartels',
    role_district_sub: 'SLA alerts & photo verification',
    role_citizen_sub: 'Project search & grievance filing',
    indic_btn: 'Indic AI',
    voice_briefing_btn: 'Voice AI',
    sign_out: 'Sign Out',
    public_portal: 'Public Transparency Portal',
    nav_back_home: 'Home / Main Portal',
    landing_hero_tag: 'AI Forensic Audit & Anomaly Detection Layer for e-SAKSHI',
    landing_hero_title: 'Continuous Forensic Vigilance. Zero Public Fund Leakage.',
    landing_hero_desc: 'An institutional command center for MPs, District Magistrates, and Central MoSPI auditors: verifying photographic progress with OpenCV 64-bit dHash, detecting contractor bidding cartels with NetworkX, and benchmarking DSR rates.',
    landing_btn_admin: 'Launch MoSPI Central Command',
    landing_btn_public: 'Explore Public Project Portal',
    landing_nav_capabilities: 'Core Capabilities',
    landing_nav_workflow: 'Audit Workflow',
    landing_nav_stats: 'National Stats',
    landing_nav_transparency: 'Public Transparency',
    landing_login: 'Login',

    // Sidebar
    suite_admin: 'National Command Suite',
    suite_district: 'District Officer Suite',
    suite_citizen: 'Citizen Navigation',
    nav_exec_dashboard: 'Executive Dashboard',
    nav_analytics: 'Intelligence Analytics',
    nav_risk_map: 'National Risk Map',
    nav_high_risk: 'High-Risk Audit Queue',
    nav_cartel_matrix: 'Cartel & Monopoly Matrix',
    nav_all_works: 'All Works Directory',
    nav_evidence_lab: 'AI Forensic Evidence Lab',
    nav_sla: 'SLA Delay Escalations',
    nav_public_reports: 'Public Vigilance Reports',
    nav_district_overview: 'District Overview',
    nav_pending_sanctions: 'Pending Sanctions',
    nav_sla_alerts: 'SLA Risk Alerts',
    nav_pre_screening: 'AI Pre-Screening',
    nav_photo_val: 'Photo Integrity Validation',
    nav_constituency_works: 'Constituency Works',
    nav_public_home: 'Public Vigilance Portal',
    nav_geo_explorer: 'Geospatial Work Explorer',
    nav_search_works: 'Search Local Works',
    nav_submit_grievance: 'Submit Citizen Grievance',

    // Dashboard Stats
    kpi_total_projects: 'Total Projects',
    kpi_total_projects_sub: 'All 28 States & UTs',
    kpi_total_funds: 'Total Funds',
    kpi_total_funds_sub: 'Sanctioned in FY 25-26',
    kpi_ai_monitored: 'AI Monitored',
    kpi_ai_monitored_sub: '95.5% Data Coverage',
    kpi_anomalies: 'Anomalies Detected',
    kpi_anomalies_sub: 'Cost, photo & cartels',
    kpi_high_risk: 'High Risk Projects',
    kpi_high_risk_sub: 'Requires immediate review',
    kpi_sla_risk: 'SLA At Risk',
    kpi_sla_risk_sub: '12 critical (<48h)',

    // 3 Column Architecture
    arch_title: 'Scheme Guard Architecture & Core Intelligence Engine',
    arch_col1_title: 'AI Analytics Engines (The Brains)',
    arch_col1_sub: 'Automated perceptual hashing & graph ML replacing subjective auditing',
    arch_col1_f1_title: 'Duplicate Image Detection (OpenCV dHash)',
    arch_col1_f1_desc: '64-bit Difference Hashing and Hamming distance cross-reference site photos across districts to instantly flag reused images.',
    arch_col1_f2_title: 'Contractor Cartel Analyzer (NetworkX)',
    arch_col1_f2_desc: 'Constructs bipartite procurement graphs and calculates Herfindahl-Hirschman Index (HHI) to expose vendor syndicates.',
    arch_col1_f3_title: 'Terrain & Climate Normalization',
    arch_col1_f3_desc: 'Calibrates anomaly thresholds for Himalayan, hill, and monsoon-disrupted districts to eliminate regional bias.',

    arch_col2_title: 'The Core Processing Engine (The Math)',
    arch_col2_sub: 'Mathematical formulation and high-speed API microservices',
    arch_col2_f1_title: 'Mathematical Risk Engine Formula',
    arch_col2_f1_desc: 'R = 0.35F + 0.25T + 0.20I + 0.20C (Financials, Timelines, Images, Contractor History) calculating a dynamic 0-100 score.',
    arch_col2_f2_title: 'Categorized Triage Tiers',
    arch_col2_f2_desc: 'Classifies works into 🔴 High Risk (>70), 🟡 Warning (40-69), and 🟢 Safe (<40) for precision officer dispatch.',
    arch_col2_f3_title: 'Live RESTful API (FastAPI)',
    arch_col2_f3_desc: 'Exposes GET /projects, POST /analyze-image, and GET /cartel-graph with interactive OpenAPI Swagger documentation.',

    arch_col3_title: 'Interactive Dashboards (The Interface)',
    arch_col3_sub: 'Enterprise GIS maps, slide-over audit sheets, and voice intelligence',
    arch_col3_f1_title: 'Geospatial District Map (Leaflet.js)',
    arch_col3_f1_desc: 'Interactive GIS map with color-coded pins displaying total funds, unspent balances, and regional risk clusters.',
    arch_col3_f2_title: 'Drill-Down Slide-Over Sheets',
    arch_col3_f2_desc: 'Granular project audit panels detailing budget vs. spend, timeline delays, photo evidence, and specific AI warning tags.',
    arch_col3_f3_title: 'Sarvam AI Sovereign Voice Intelligence',
    arch_col3_f3_desc: 'Multilingual TTS audio briefings and Saaras ASR vernacular grievance speech processing for rural citizens.',

    // Judge Defense Panel
    judge_title: 'Systemic Vulnerability & Judge Defense Mitigations',
    judge_sub: 'Engineered solutions to real-world edge cases, location-spoofing, and human biases',
    judge_d1_title: '1. Editable Geotags (GPS Spoofing)',
    judge_d1_desc: 'Multi-Source Spatial Attestation cross-verifies EXIF GPS coordinates against cellular tower IDs, ISP telemetry, and PostGIS polygon boundaries, rejecting spoofed uploads.',
    judge_d2_title: '2. Human-in-the-Loop Bribery',
    judge_d2_desc: 'Multi-Signature Dual-Auditor Protocol mandates two independent officer digital signatures (e-Sign) to override alerts, writing to an immutable audit trail.',
    judge_d3_title: '3. AI-Generated Construction Photos',
    judge_d3_desc: 'Forensic Frequency Domain Analysis inspects FFT spectral artifacts and Error Level Analysis (ELA) against baseline Day-0 terrain satellite captures.',
    judge_d4_title: '4. Terrain & Monsoon Regional Bias',
    judge_d4_desc: 'Context-Aware Baseline Normalization adjusts delay thresholds via Terrain Difficulty & Monsoon Disruption factors so hill/remote districts are not penalized.',

    // Table & General UI
    table_work_id: 'Work ID',
    table_desc_constituency: 'Description & Constituency',
    table_sanction_value: 'Sanction Value',
    table_composite_risk: 'Composite Risk',
    table_status: 'Audit Status',
    table_actions: 'Actions',
    btn_audit: 'Audit Dossier',
    btn_export: 'Export Report',
    btn_refresh: 'Refresh Live Data',
    filter_all_states: 'All States & UTs',
    filter_risk_level: 'All Risk Levels',
    footer_text: 'SCHEME GUARD AI MONITOR — Ministry of Statistics and Programme Implementation (MoSPI) • Govt. of India',
    footer_sec: 'RESTRICTED GOVERNMENT AUDIT ACCESS • ZERO-LEAKAGE ALLOCATION',

    // Home Page Translations
    home_nav_home: 'Home',
    home_nav_methodology: 'Methodology & Working Principle',
    home_nav_about: 'About the Scheme',
    home_nav_contact: 'Contact',
    home_hero_title: 'Scheme Guard: From Local Priorities to National Development',
    home_hero_sub: 'Algorithmic vigilance, real-time PFMS treasury tracking, and image forensics protecting public development assets across all 543 Lok Sabha Constituencies.',
    btn_district_cmd: 'Launch District Command',
    home_box_guidelines: 'Guidelines & Acts',
    home_box_guidelines_sub: '2023 Revised Protocol',
    home_box_voice: 'Voice AI Assist',
    home_box_voice_sub: '8 Indic Languages',
    home_box_citizen: 'Citizen Request',
    home_box_citizen_sub: 'Local Area Proposal',
    home_box_audit: 'AI Audit Dossier',
    home_box_audit_sub: 'Flagged NANDURBAR',
    home_ticker_badge: 'Live Surveillance',
    home_ticker_strong: 'MoSPI e-SAKSHI 2.0 Alert:',
    home_ticker_desc: 'Surveillance active across 543 Lok Sabha Constituencies • ₹83,336.67 Cr funds continuously monitored • Project MPLAD-2026-00124 (Nandurbar) flagged with 87% composite risk due to duplicate image detection • TSA/Hybrid ‘just-in-time’ fund disbursal protocol integrated with PFMS, RBI and SBI.',
    home_kpi_heading: 'National Developmental Indicators & Fund Flow',
    home_kpi_sub: "Live statistics of works recommended online by Hon'ble Members of Parliament under revised TSA fund procedure",
    kpi_tab_statutory: 'Statutory e-SAKSHI View',
    kpi_tab_vigilance: 'AI Vigilance Layer',
    kpi_sabha_lok: 'Lok Sabha (543 MPs)',
    kpi_sabha_rajya: 'Rajya Sabha (245 MPs)',
    kpi_entitlement: 'Entitlement (FY)',
    kpi_entitlement_sub: 'Per MP / Year',
    kpi_tsa_fund: 'TSA Pooled Fund',
    kpi_tsa_fund_sub: 'Active Allocations',
    kpi_works_rec: 'Works Recommended',
    kpi_works_rec_sub: 'Digital Submissions',
    kpi_works_sanc: 'Works Sanctioned',
    kpi_works_sanc_sub: 'Feasibility Passed',
    kpi_works_comp: 'Works Completed',
    kpi_works_comp_sub: 'Assets Built & Verified',
    kpi_expenditure: 'Total Expenditure',
    kpi_expenditure_sub: 'PFMS Disbursals',
    kpi_ai_monitored_title: 'AI Monitored Works',
    kpi_ai_monitored_desc: '100% Geotagged MBs',
    kpi_anomalies_title: 'Anomalies Flagged',
    kpi_anomalies_desc: 'Continuous Watch',
    kpi_high_risk_title: 'High-Risk Queue',
    kpi_high_risk_desc: 'Composite > 70',
    kpi_cartels_title: 'Cartels Detected',
    kpi_cartels_desc: 'HHI Index > 2500',
    kpi_dup_title: 'Duplicate Intercept',
    kpi_dup_desc: 'OpenCV 64-bit dHash',
    kpi_hold_title: 'Disbursals on Hold',
    kpi_hold_desc: 'Milestone Holds',
    home_how_it_works: 'How It Works: Continuous Vigilance & Public Fund Safeguards',
    home_about_title: 'About Scheme Guard',
    home_statutory_overview: 'Statutory Overview',
    brand_sub_short: 'Ministry of Statistics & Programme Implementation',
    home_viksit_bharat: 'Viksit Bharat @ 2047 Alignment:',
    home_viksit_desc: 'The Scheme encourages MPs to prioritize future-ready, green, and sustainable infrastructure that supports grassroots social equity and self-reliance.',
    arch_main_heading: 'Smarter Monitoring. Transparent Funds.',
    arch_tag_projects: 'Real projects.',
    arch_tag_impact: 'Real impact.',
    arch_col1_heading: 'Evidence & Fraud Checks',
    arch_col2_heading: 'AI Risk Scoring Models',
    arch_col3_heading: 'Interactive Dashboards & Voice AI',
    arch_btn_evidence: 'Open Forensic Evidence Lab',
    arch_btn_dossier: 'Open Sample Audit Dossier',
  },

  'hi-IN': {
    brand_title: 'एमपीलैड्स इंटेलिजेंस',
    brand_tag: 'सांख्यिकी मंत्रालय e-SAKSHI लेयर',
    brand_sub: 'सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय • भारत सरकार',
    search_placeholder: 'परियोजना आईडी, ज़िला, ठेकेदार, कार्टेल खोजें...',
    role_admin: 'MoSPI केंद्रीय लेखापरीक्षक',
    role_district: 'ज़िलाधिकारी (DM)',
    role_citizen: 'नागरिक पोर्टल',
    role_persona: 'सक्रिय प्रशासनिक भूमिका',
    role_admin_sub: 'राष्ट्रीय निगरानी व कार्टेल विश्लेषण',
    role_district_sub: 'एसएलए अलर्ट व फोटो सत्यापन',
    role_citizen_sub: 'परियोजना खोज व नागरिक शिकायत',
    indic_btn: 'सर्वम AI',
    voice_briefing_btn: 'ध्वनि AI',
    sign_out: 'लॉग आउट',
    public_portal: 'सार्वजनिक पारदर्शिता पोर्टल',
    nav_back_home: 'मुख्य पृष्ठ / होम',
    landing_hero_tag: 'ई-साक्षी (e-SAKSHI) के लिए एआई फोरेंसिक ऑडिट एवं विसंगति पहचान प्रणाली',
    landing_hero_title: 'निरंतर फोरेंसिक सतर्कता। शून्य सार्वजनिक धन रिसाव।',
    landing_hero_desc: 'सांसदों, जिलाधिकारियों और केंद्रीय सांख्यिकी मंत्रालय (MoSPI) लेखापरीक्षकों के लिए संस्थागत कमान केंद्र: OpenCV 64-बिट dHash से साइट फोटो सत्यापन, NetworkX से ठेकेदार कार्टेल जांच और DSR दर विश्लेषण।',
    landing_btn_admin: 'MoSPI केंद्रीय कमान प्रारंभ करें',
    landing_btn_public: 'सार्वजनिक नागरिक पोर्टल देखें',
    landing_nav_capabilities: 'प्रमुख क्षमताएं',
    landing_nav_workflow: 'ऑडिट कार्यप्रवाह',
    landing_nav_stats: 'राष्ट्रीय आंकड़े',
    landing_nav_transparency: 'सार्वजनिक पारदर्शिता',
    landing_login: 'अधिकारी लॉगिन',

    suite_admin: 'राष्ट्रीय कमान केंद्र',
    suite_district: 'ज़िलाधिकारी नियंत्रण कक्ष',
    suite_citizen: 'नागरिक सेवा केंद्र',
    nav_exec_dashboard: 'कार्यकारी डैशबोर्ड',
    nav_analytics: 'खुफिया विश्लेषण',
    nav_risk_map: 'राष्ट्रीय जोखिम मानचित्र',
    nav_high_risk: 'उच्च जोखिम ऑडिट कतार',
    nav_cartel_matrix: 'ठेकेदार कार्टेल व सिंडिकेट',
    nav_all_works: 'सभी स्वीकृत कार्य',
    nav_evidence_lab: 'एआई फोरेंसिक साक्ष्य प्रयोगशाला',
    nav_sla: 'समय-सीमा (SLA) उल्लंघन अलर्ट',
    nav_district_overview: 'ज़िला समग्र विवरण',
    nav_pending_sanctions: 'लंबित स्वीकृतियां',
    nav_sla_alerts: 'समय-सीमा जोखिम अलर्ट',
    nav_pre_screening: 'एआई प्रारंभिक जांच',
    nav_photo_val: 'फोटो सत्यता सत्यापन',
    nav_constituency_works: 'संसदीय क्षेत्र कार्य',
    nav_public_home: 'सार्वजनिक सतर्कता पोर्टल',
    nav_geo_explorer: 'मानचित्र कार्य अन्वेषक',
    nav_search_works: 'स्थानीय विकास कार्य खोजें',
    nav_submit_grievance: 'नागरिक शिकायत दर्ज करें',

    kpi_total_projects: 'कुल स्वीकृत परियोजनाएं',
    kpi_total_projects_sub: 'सभी 28 राज्य व केंद्र शासित प्रदेश',
    kpi_total_funds: 'कुल स्वीकृत निधि',
    kpi_total_funds_sub: 'वित्तीय वर्ष 2025-26 में जारी',
    kpi_ai_monitored: 'एआई द्वारा निरंतर निगरानी',
    kpi_ai_monitored_sub: '95.5% डेटा आच्छादन',
    kpi_anomalies: 'पहचानी गई विसंगतियां',
    kpi_anomalies_sub: 'लागत, फोटो व कार्टेल संकेंद्रण',
    kpi_high_risk: 'उच्च जोखिम परियोजनाएं',
    kpi_high_risk_sub: 'तत्काल निरीक्षण आवश्यक',
    kpi_sla_risk: 'समय-सीमा उल्लंघन जोखिम',
    kpi_sla_risk_sub: '12 अति-गंभीर (<48 घंटे)',

    arch_title: 'एमपीलैड सेंटिनल संरचना एवं कोर इंटेलिजेंस इंजन',
    arch_subtitle: 'त्रि-स्तंभीय सतत ऑडिट वास्तुकला: एआई एनालिटिक्स, गणितीय जोखिम गणना, और भू-स्थानिक इंटरफ़ेस',
    arch_col1_title: 'स्तंभ 1: एआई एनालिटिक्स इंजन (बुद्धिमत्ता)',
    arch_col1_sub: 'पारंपरिक मानवीय जांच के स्थान पर स्वचालित कंप्यूटर विज़न एवं ग्राफ एमएल',
    arch_col1_f1_title: 'डुप्लीकेट फोटो पहचान (OpenCV dHash)',
    arch_col1_f1_desc: '64-बिट डिफरेंस हैशिंग और हैमिंग दूरी द्वारा विभिन्न ज़िलों की तस्वीरों का मिलान कर पुरानी तस्वीरों के पुन: उपयोग को तुरंत पकड़ता है।',
    arch_col1_f2_title: 'ठेकेदार कार्टेल विश्लेषक (NetworkX)',
    arch_col1_f2_desc: 'निविदा संबंधों का द्विदलीय (Bipartite) ग्राफ बनाकर हरफिंडाहल-हर्शमैन इंडेक्स (HHI) द्वारा ज़िले में ठेकेदारों के एकाधिकार को उजागर करता है।',
    arch_col1_f3_title: 'भौगोलिक व मानसूनी सामान्यीकरण',
    arch_col1_f3_desc: 'पहाड़ी, दुर्गम और मानसूनी क्षेत्रों के लिए थ्रेशोल्ड समायोजित करता है ताकि भौगोलिक कारणों से होने वाले विलंब को गलत तरीके से धोखाधड़ी न माना जाए।',

    arch_col2_title: 'स्तंभ 2: कोर प्रोसेसिंग इंजन (गणितीय मॉडल)',
    arch_col2_sub: 'वैज्ञानिक जोखिम सूत्र एवं तीव्र गति फास्ट-एपीआई सेवाएं',
    arch_col2_f1_title: 'गणितीय जोखिम गणना सूत्र',
    arch_col2_f1_desc: 'R = 0.35F + 0.25T + 0.20I + 0.20C (वित्तीय अनियमितता, समय-सीमा, फोटो अंतर, ठेकेदार इतिहास) पर आधारित 0-100 गतिशील स्कोर।',
    arch_col2_f2_title: 'त्रि-स्तरीय प्राथमिकता श्रेणियां',
    arch_col2_f2_desc: 'परियोजनाओं को 🔴 उच्च जोखिम (>70), 🟡 चेतावनी (40-69), और 🟢 सुरक्षित (<40) में विभाजित कर अधिकारियों को सटीक दिशा देता है।',
    arch_col2_f3_title: 'लाइव रेस्टफुल एपीआई (FastAPI)',
    arch_col2_f3_desc: 'उच्च गति वाले GET /projects, POST /analyze-image, एवं GET /cartel-graph एंडपॉइंट्स स्वैगर प्रलेखन के साथ सक्रिय हैं।',

    arch_col3_title: 'स्तंभ 3: संवादात्मक डैशबोर्ड (यूजर इंटरफ़ेस)',
    arch_col3_sub: 'संस्थागत जीआईएस मानचित्र, स्लाइड-ओवर ऑडिट पैनल, और बहुभाषी सर्वम वॉयस एआई',
    arch_col3_f1_title: 'भू-स्थानिक ज़िला मानचित्र (Leaflet.js)',
    arch_col3_f1_desc: 'रंग-कोडित पिनों के साथ संवादात्मक जीआईएस मानचित्र जो कुल स्वीकृत राशि, अप्रयुक्त शेष, और जोखिम समूहों को प्रदर्शित करता है।',
    arch_col3_f2_title: 'ड्रिल-डाउन स्लाइड-ओवर ऑडिट पैनल',
    arch_col3_f2_desc: 'प्रत्येक परियोजना की गहराई से जांच के लिए बजट बनाम खर्च, समय-सीमा विलंब, फोटो साक्ष्य, और एआई चेतावनी टैग दिखाता है।',
    arch_col3_f3_title: 'सर्वम एआई संप्रभु ध्वनि बुद्धिमत्ता',
    arch_col3_f3_desc: 'अधिकारियों के लिए बहुभाषी ऑडियो ब्रीफिंग (TTS) और ग्रामीण नागरिकों के लिए सारास ASR द्वारा क्षेत्रीय भाषा में ध्वनि शिकायत निवारण।',

    judge_title: 'प्रणालीगत संवेदनशीलता व जूरी रक्षा समाधान (Judge Defense)',
    judge_sub: 'वास्तविक जीवन की चुनौतियों, स्थान धोखाधड़ी (GPS Spoofing), और रिश्वतखोरी के विरुद्ध तकनीकी समाधान',
    judge_d1_title: '1. संपादन योग्य जियोटैग (GPS Spoofing का समाधान)',
    judge_d1_desc: 'बहु-स्रोत स्थानिक सत्यापन: EXIF जीपीएस निर्देशांकों का मोबाइल टावर आईडी, इंटरनेट प्रदाता आईपी और पोस्ट-जीआईएस ज़िला बहुभुज सीमाओं से त्रि-स्तरीय मिलान करता है।',
    judge_d2_title: '2. मानवीय रिश्वतखोरी रोकथाम (Human Bribery Prevention)',
    judge_d2_desc: 'मल्टी-सिग्नेचर डुअल-ऑडिटर प्रोटोकॉल: एआई अलर्ट को खारिज करने के लिए दो स्वतंत्र अधिकारियों के डिजिटल हस्ताक्षर (e-Sign) अनिवार्य हैं, जो अपरिवर्तनीय ऑडिट ट्रेल में दर्ज होते हैं।',
    judge_d3_title: '3. एआई जनरेटेड फर्जी फोटो पहचान (Deepfake Detection)',
    judge_d3_desc: 'फोरेंसिक फ्रीक्वेंसी डोमेन विश्लेषण: एफएफटी (FFT) स्पेक्ट्रल विश्लेषण और एरर लेवल एनालिसिस (ELA) द्वारा जनरेटिव एआई पिक्सल विसंगतियों को डे-0 बेसलाइन तस्वीरों से मिलाता है।',
    judge_d4_title: '4. पहाड़ी व मानसूनी क्षेत्रों में क्षेत्रीय निष्पक्षता',
    judge_d4_desc: 'संदर्भ-जागरूक सामान्यीकरण: कठिन भूभाग व वर्षा बाधा सूचकांक को लागू करता है ताकि पूर्वोत्तर और हिमालयी राज्यों को प्राकृतिक कठिनाई के लिए दंडित न किया जाए।',

    table_work_id: 'कार्य पहचान (ID)',
    table_desc_constituency: 'विवरण व संसदीय क्षेत्र',
    table_sanction_value: 'स्वीकृत राशि',
    table_composite_risk: 'समग्र जोखिम',
    table_status: 'ऑडिट स्थिति',
    table_actions: 'कार्रवाई',
    btn_audit: 'ऑडिट डॉसियर',
    btn_export: 'रिपोर्ट डाउनलोड करें',
    btn_refresh: 'लाइव डेटा रीफ्रेश करें',
    filter_all_states: 'सभी राज्य व संघ राज्य',
    filter_risk_level: 'सभी जोखिम स्तर',
    footer_text: 'एमपीलैड्स एआई मॉनिटर — सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) • भारत सरकार',
    footer_sec: 'प्रतिबंधित सरकारी ऑडिट पहुंच • शून्य वित्तीय रिसाव संकल्प',

    // Home Page Translations
    home_nav_home: 'होम',
    home_nav_methodology: 'कार्यप्रणाली एवं सिद्धांत',
    home_nav_about: 'योजना का विवरण',
    home_nav_contact: 'संपर्क',
    home_hero_title: 'स्कीम गार्ड: स्थानीय प्राथमिकताओं से राष्ट्रीय विकास तक',
    home_hero_sub: 'सभी 543 लोकसभा क्षेत्रों में विकास संपत्तियों की सुरक्षा: कलनविधि निगरानी, पीएफएमएस वास्तविक समय ट्रेजरी ट्रैकिंग और फोटो फोरेंसिक।',
    btn_district_cmd: 'ज़िला कमान प्रारंभ करें',
    home_box_guidelines: 'दिशानिर्देश एवं अधिनियम',
    home_box_guidelines_sub: '2023 संशोधित प्रोटोकॉल',
    home_box_voice: 'ध्वनि AI सहायता',
    home_box_voice_sub: '8 भारतीय भाषाएं',
    home_box_citizen: 'नागरिक अनुरोध',
    home_box_citizen_sub: 'स्थानीय क्षेत्र प्रस्ताव',
    home_box_audit: 'एआई ऑडिट डॉसियर',
    home_box_audit_sub: 'चिह्नित नंदुरबार',
    home_ticker_badge: 'लाइव निगरानी',
    home_ticker_strong: 'MoSPI ई-साक्षी 2.0 अलर्ट:',
    home_ticker_desc: 'सभी 543 लोकसभा क्षेत्रों में सक्रिय निगरानी • ₹83,336.67 करोड़ निधि की निरंतर मॉनिटरिंग • परियोजना MPLAD-2026-00124 (नंदुरबार) डुप्लीकेट फोटो के कारण 87% समग्र जोखिम पर चिह्नित • PFMS, RBI और SBI के साथ एकीकृत TSA जस्ट-इन-टाइम संवितरण।',
    home_kpi_heading: 'राष्ट्रीय विकास संकेतक एवं निधि प्रवाह',
    home_kpi_sub: 'संशोधित टीएसए प्रक्रिया के अंतर्गत माननीय सांसदों द्वारा ऑनलाइन अनुशंसित कार्यों के वास्तविक आंकड़े',
    kpi_tab_statutory: 'सांविधिक ई-साक्षी दृश्य',
    kpi_tab_vigilance: 'एआई सतर्कता लेयर',
    kpi_sabha_lok: 'लोकसभा (543 सांसद)',
    kpi_sabha_rajya: 'राज्यसभा (245 सांसद)',
    kpi_entitlement: 'वार्षिक पात्रता (FY)',
    kpi_entitlement_sub: 'प्रति सांसद / वर्ष',
    kpi_tsa_fund: 'टीएसए संचित निधि',
    kpi_tsa_fund_sub: 'सक्रिय आवंटन',
    kpi_works_rec: 'अनुशंसित कार्य',
    kpi_works_rec_sub: 'डिजिटल प्रस्तुतियां',
    kpi_works_sanc: 'स्वीकृत कार्य',
    kpi_works_sanc_sub: 'तकनीकी स्वीकृति पूर्ण',
    kpi_works_comp: 'पूर्ण हुए कार्य',
    kpi_works_comp_sub: 'निर्मित व सत्यापित संपत्तियां',
    kpi_expenditure: 'कुल व्यय',
    kpi_expenditure_sub: 'पीएफएमएस संवितरण',
    kpi_ai_monitored_title: 'एआई द्वारा निगरानी कार्य',
    kpi_ai_monitored_desc: '100% जियोटैग मापन पुस्तकें',
    kpi_anomalies_title: 'पहचानी गई विसंगतियां',
    kpi_anomalies_desc: 'निरंतर निगरानी',
    kpi_high_risk_title: 'उच्च जोखिम कतार',
    kpi_high_risk_desc: 'समग्र स्कोर > 70',
    kpi_cartels_title: 'ठेकेदार कार्टेल पहचाने गए',
    kpi_cartels_desc: 'एचएचआई सूचकांक > 2500',
    kpi_dup_title: 'डुप्लीकेट फोटो अवरोध',
    kpi_dup_desc: 'ओपन-सीवी 64-बिट dHash',
    kpi_hold_title: 'रोकी गई धनराशि',
    kpi_hold_desc: 'मील का पत्थर सत्यापन लंबित',
    home_how_it_works: 'यह कैसे कार्य करता है: निरंतर सतर्कता एवं सार्वजनिक धन सुरक्षा',
    home_about_title: 'स्कीम गार्ड के बारे में',
    home_statutory_overview: 'सांविधिक विवरण',
    brand_sub_short: 'सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय',
    home_viksit_bharat: 'विकसित भारत @ 2047 संरेखण:',
    home_viksit_desc: 'यह योजना सांसदों को भविष्य के लिए तैयार, हरित और टिकाऊ बुनियादी ढांचे को प्राथमिकता देने के लिए प्रोत्साहित करती है।',
    arch_main_heading: 'स्मार्ट निगरानी। पारदर्शी निधि।',
    arch_tag_projects: 'सत्यापित कार्य।',
    arch_tag_impact: 'वास्तविक प्रभाव।',
    arch_col1_heading: 'साक्ष्य एवं धोखाधड़ी रोकथाम',
    arch_col2_heading: 'एआई जोखिम गणना मॉडल',
    arch_col3_heading: 'संवादात्मक डैशबोर्ड व वॉयस एआई',
    arch_btn_evidence: 'फोरेंसिक साक्ष्य प्रयोगशाला खोलें',
    arch_btn_dossier: 'नमूना ऑडिट डॉसियर देखें',
  },

  'mr-IN': {
    brand_title: 'खासदार निधी इंटेलिजेंस',
    brand_tag: 'सांख्यिकी मंत्रालय e-SAKSHI लेयर',
    brand_sub: 'सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय • भारत सरकार',
    search_placeholder: 'प्रकल्प क्रमांक, जिल्हा, कंत्राटदार शोधा...',
    role_admin: 'MoSPI केंद्रीय लेखापरीक्षक',
    role_district: 'जिल्हाधिकारी (DM)',
    role_citizen: 'नागरिक पोर्टल',
    role_persona: 'सक्रिय प्रशासकीय भूमिका',
    role_admin_sub: 'राष्ट्रीय देखरेख आणि कार्टेल शोध',
    role_district_sub: 'SLA इशारे व फोटो पडताळणी',
    role_citizen_sub: 'प्रकल्प शोध व नागरिक तक्रार',
    indic_btn: 'सर्वम AI',
    voice_briefing_btn: 'व्हॉइस AI',
    sign_out: 'लॉग आउट',
    sec_profile: 'सुरक्षा आणि प्रोफाइल',
    public_portal: 'सार्वजनिक पारदर्शकता पोर्टल',

    suite_admin: 'राष्ट्रीय आदेश कक्ष',
    suite_district: 'जिल्हाधिकारी नियंत्रण कक्ष',
    suite_citizen: 'नागरिक सेवा केंद्र',
    nav_exec_dashboard: 'कार्यकारी डॅशबोर्ड',
    nav_analytics: 'बुद्धिमत्ता विश्लेषण',
    nav_risk_map: 'राष्ट्रीय जोखीम नकाशा',
    nav_high_risk: 'अति-जोखीम तपासणी यादी',
    nav_cartel_matrix: 'कंत्राटदार मक्तेदारी (कार्टेल)',
    nav_all_works: 'सर्व मंजूर कामे',
    nav_evidence_lab: 'न्यायवैद्यक पुरावा प्रयोगशाळा',
    nav_sla: 'मुदतवाढ उल्लंघन इशारे',
    nav_district_overview: 'जिल्हा आढावा',
    nav_pending_sanctions: 'प्रलंबित मंजुऱ्या',
    nav_sla_alerts: 'मुदत जोखीम इशारे',
    nav_pre_screening: 'एआय प्राथमिक तपासणी',
    nav_photo_val: 'छायाचित्र सत्यता पडताळणी',
    nav_constituency_works: 'मतदारसंघ विकास कामे',
    nav_public_home: 'सार्वजनिक दक्षता पोर्टल',
    nav_geo_explorer: 'भौगोलिक कामे शोधक',
    nav_search_works: 'स्थानिक कामे शोधा',
    nav_submit_grievance: 'नागरिक तक्रार नोंदवा',

    kpi_total_projects: 'एकूण मंजूर प्रकल्प',
    kpi_total_projects_sub: 'सर्व २८ राज्ये व केंद्रशासित प्रदेश',
    kpi_total_funds: 'एकूण मंजूर निधी',
    kpi_total_funds_sub: 'आर्थिक वर्ष २०२५-२६ मध्ये वितरित',
    kpi_ai_monitored: 'एआय द्वारे सतत देखरेख',
    kpi_ai_monitored_sub: '९५.५% डेटा संरक्षण',
    kpi_anomalies: 'आढळलेल्या अनियमितता',
    kpi_anomalies_sub: 'खर्च, फोटो व कार्टेल मक्तेदारी',
    kpi_high_risk: 'अति-जोखीम प्रकल्प',
    kpi_high_risk_sub: 'तातडीने प्रत्यक्ष तपासणी आवश्यक',
    kpi_sla_risk: 'मुदत उल्लंघन जोखीम',
    kpi_sla_risk_sub: '१२ गंभीर (<४८ तास)',

    arch_title: 'एमपीलॅड सेंटिनेल रचना आणि कोर इंटेलिजन्स इंजिन',
    arch_subtitle: 'त्रि-स्तरीय अखंड लेखापरीक्षण: एआय विश्लेषण, गणितीय जोखीम गणना, आणि भौगोलिक इंटरफेस',
    arch_col1_title: 'स्तंभ १: एआय अनॅलिटिक्स इंजिन (बुद्धिमत्ता)',
    arch_col1_sub: 'मानवी तपासणीऐवजी स्वयंचलित कॉम्प्युटर व्हिजन आणि नेटवर्क ग्राफ',
    arch_col1_f1_title: 'दुबार छायाचित्र शोध (OpenCV dHash)',
    arch_col1_f1_desc: '६४-बिट डिफरन्स हॅशिंगद्वारे विविध जिल्ह्यातील छायाचित्रांची तुलना करून जुन्या फोटोंचा गैरवापर रोखते.',
    arch_col1_f2_title: 'कंत्राटदार कार्टेल विश्लेषक (NetworkX)',
    arch_col1_f2_desc: 'निविदांचा द्विपक्षीय आलेख तयार करून हर्फ़िंडाहल इंडेक्स (HHI) द्वारे मक्तेदारी उघडकीस आणते.',
    arch_col1_f3_title: 'भौगोलिक व हवामान सामान्यीकरण',
    arch_col1_f3_desc: 'डोंगराळ व पावसाळी भागातील नैसर्गिक विलंबाचा निष्पक्ष विचार करून थ्रेशोल्ड निश्चित करते.',

    arch_col2_title: 'स्तंभ २: कोर प्रोसेसिंग इंजिन (गणितीय मॉडेल)',
    arch_col2_sub: 'अचूक जोखीम सूत्र आणि वेगवान फास्ट-एपीआय सेवा',
    arch_col2_f1_title: 'गणितीय जोखीम गणना सूत्र',
    arch_col2_f1_desc: 'R = 0.35F + 0.25T + 0.20I + 0.20C या सूत्राने ० ते १०० दरम्यान गतिशील गुण दिले जातात.',
    arch_col2_f2_title: 'त्रि-स्तरीय प्राधान्य वर्गवारी',
    arch_col2_f2_desc: 'प्रकल्पांची 🔴 अति-जोखीम (>७०), 🟡 इशारा (४०-६९), आणि 🟢 सुरक्षित (<४०) अशी विभागणी होते.',
    arch_col2_f3_title: 'थेट रेस्टफुल एपीआय (FastAPI)',
    arch_col2_f3_desc: 'GET /projects, POST /analyze-image, आणि GET /cartel-graph एंडपॉइंट्स स्वॅगरसह उपलब्ध आहेत.',

    arch_col3_title: 'स्तंभ ३: संवादात्मक डॅशबोर्ड (इंटरफेस)',
    arch_col3_sub: 'संस्थात्मक जीआयएस नकाशे, स्लाइड-ओवर ऑडिट पॅनल, आणि व्हॉइस एआय',
    arch_col3_f1_title: 'भौगोलिक जिल्हा नकाशा (Leaflet.js)',
    arch_col3_f1_desc: 'रंगीत चिन्हांसह संवादात्मक नकाशा जो निधी वापर आणि प्रादेशिक जोखीम दाखवतो.',
    arch_col3_f2_title: 'तपशीलवार स्लाइड-ओवर ऑडिट पॅनल',
    arch_col3_f2_desc: 'खर्च, मुदत विलंब, छायाचित्र पुरावे आणि एआय इशारे एका क्लिकवर समोर आणते.',
    arch_col3_f3_title: 'सर्वम एआय संप्रभू व्हॉइस इंटेलिजन्स',
    arch_col3_f3_desc: 'मराठीत ऑडिओ अहवाल (TTS) आणि सारास ASR द्वारे ग्रामीण नागरिकांच्या आवाजी तक्रारींचे निवारण.',

    judge_title: 'प्रणालीगत आव्हाने आणि ज्युरी संरक्षण उपाय',
    judge_sub: 'खोट्या जीपीएस नोंदी, मानवी भ्रष्टाचार, आणि एआय डीपफेक छायाचित्रांविरुद्ध ठोस उपाय',
    judge_d1_title: '१. खोट्या जिओटॅग नोंदी (GPS Spoofing)',
    judge_d1_desc: 'मोबाइल टॉवर आयडी, इंटरनेट आयपी आणि पोस्ट-जीआयएस सीमा यांच्याशी तिहेरी पडताळणी.',
    judge_d2_title: '२. मानवी भ्रष्टाचार प्रतिबंध (Bribery Prevention)',
    judge_d2_desc: 'दोन स्वतंत्र अधिकाऱ्यांच्या डिजिटल स्वाक्षरी (e-Sign) शिवाय अलर्ट रद्द करता येत नाही.',
    judge_d3_title: '३. एआय जनरेटेड बनावट छायाचित्रे (Deepfake)',
    judge_d3_desc: 'एफएफटी स्पेक्ट्रल विश्लेषण आणि एरर लेव्हल ॲनालिसिसद्वारे कृत्रिम पिक्सेल लगेच पकडले जातात.',
    judge_d4_title: '४. डोंगराळ व दुर्गम भागातील नैसर्गिक विलंब',
    judge_d4_desc: 'कठीण भौगोलिक परिस्थितीचा घटक जोडून निष्पक्ष मूल्यमापन केले जाते.',

    table_work_id: 'काम क्र.',
    table_desc_constituency: 'तपशील व मतदारसंघ',
    table_sanction_value: 'मंजूर रक्कम',
    table_composite_risk: 'एकत्रित जोखीम',
    table_status: 'स्थिती',
    table_actions: 'कृती',
    btn_audit: 'तपासणी डॉसियर',
    btn_export: 'अहवाल डाउनलोड',
    btn_refresh: 'माहिती अद्ययावत करा',
    filter_all_states: 'सर्व राज्ये',
    filter_risk_level: 'सर्व जोखीम स्तर',
    footer_text: 'एमपीलॅड्स एआय मॉनिटर — सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय (MoSPI) • भारत सरकार',
    footer_sec: 'प्रतिबंधित सरकारी प्रवेश • शून्य निधी गळती ध्येय',

    // Home Page Translations
    home_nav_home: 'मुख्य पृष्ठ',
    home_nav_methodology: 'कार्यपद्धती आणि तत्त्वे',
    home_nav_about: 'योजनेविषयी माहिती',
    home_nav_contact: 'संपर्क',
    home_hero_title: 'स्कीम गार्ड: स्थानिक गरजांपासून राष्ट्रीय विकासाकडे',
    home_hero_sub: 'सर्व ५४३ लोकसभा मतदारसंघांत विकास निधीची सुरक्षा: अल्गोरिथमिक दक्षता, रिअल-टाइम PFMS ट्रॅकिंग आणि छायाचित्र न्यायवैद्यक तपासणी.',
    btn_district_cmd: 'जिल्हा नियंत्रण कक्ष उघडा',
    home_box_guidelines: 'मार्गदर्शक तत्त्वे व कायदे',
    home_box_guidelines_sub: '२०२३ सुधारित प्रोटोकॉल',
    home_box_voice: 'व्हॉइस एआय मदत',
    home_box_voice_sub: '८ भारतीय भाषा',
    home_box_citizen: 'नागरिक विनंती',
    home_box_citizen_sub: 'स्थानिक विकास प्रस्ताव',
    home_box_audit: 'एआय ऑडिट डॉसियर',
    home_box_audit_sub: 'चिन्हांकित नंदुरबार',
    home_ticker_badge: 'थेट देखरेख',
    home_ticker_strong: 'MoSPI e-SAKSHI २.० अलर्ट:',
    home_ticker_desc: 'सर्व ५४३ लोकसभा मतदारसंघांवर थेट नजर • ₹८३,३३६.६७ कोटी निधीची सतत देखरेख • नंदुरबार प्रकल्प दुबार फोटोंमुळे ८७% जोखमीवर चिन्हांकित • PFMS, RBI आणि SBI द्वारे TSA थेट निधी वितरण.',
    home_kpi_heading: 'राष्ट्रीय विकास निर्देशांक आणि निधी प्रवाह',
    home_kpi_sub: 'सुधारित TSA प्रक्रियेअंतर्गत माननीय खासदारांनी ऑनलाइन शिफारस केलेल्या कामांची थेट आकडेवारी',
    kpi_tab_statutory: 'वैधानिक e-SAKSHI दृश्य',
    kpi_tab_vigilance: 'एआय दक्षता लेयर',
    kpi_sabha_lok: 'लोकसभा (५४३ खासदार)',
    kpi_sabha_rajya: 'राज्यसभा (२४५ खासदार)',
    kpi_entitlement: 'वार्षिक पात्रता (FY)',
    kpi_entitlement_sub: 'प्रति खासदार / वर्ष',
    kpi_tsa_fund: 'TSA संचित निधी',
    kpi_tsa_fund_sub: 'सक्रिय वाटप',
    kpi_works_rec: 'शिफारस केलेली कामे',
    kpi_works_rec_sub: 'डिजिटल नोंदी',
    kpi_works_sanc: 'मंजूर कामे',
    kpi_works_sanc_sub: 'तांत्रिक मान्यता पूर्ण',
    kpi_works_comp: 'पूर्ण झालेली कामे',
    kpi_works_comp_sub: 'प्रत्यक्ष पूर्ण व सत्यापित',
    kpi_expenditure: 'एकूण खर्च',
    kpi_expenditure_sub: 'PFMS वितरण',
    kpi_ai_monitored_title: 'एआय देखरेख कामे',
    kpi_ai_monitored_desc: '१००% जिओटॅग मोजमाप पुस्तिका',
    kpi_anomalies_title: 'नोंदवलेल्या अनियमितता',
    kpi_anomalies_desc: 'सतत लक्ष',
    kpi_high_risk_title: 'अति-जोखीम यादी',
    kpi_high_risk_desc: 'एकत्रित गुण > ७०',
    kpi_cartels_title: 'कंत्राटदार कार्टेल शोध',
    kpi_cartels_desc: 'HHI निर्देशांक > २५००',
    kpi_dup_title: 'दुबार फोटो शोध',
    kpi_dup_desc: 'OpenCV ६४-बिट dHash',
    kpi_hold_title: 'स्थगित निधी',
    kpi_hold_desc: 'टप्पा पडताळणी प्रलंबित',
    home_how_it_works: 'हे कसे कार्य करते: अखंड दक्षता आणि सार्वजनिक निधी सुरक्षा',
    home_about_title: 'स्कीम गार्ड विषयी',
    home_statutory_overview: 'वैधानिक आढावा',
    brand_sub_short: 'सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय',
    home_viksit_bharat: 'विकसित भारत @ २०४७ उद्दिष्ट:',
    home_viksit_desc: 'खासदार निधी योजनेअंतर्गत भविष्यवेधी, पर्यावरणपूरक आणि शाश्वत पायाभूत सुविधांच्या विकासाला प्राधान्य दिले जाते.',
    arch_main_heading: 'स्मार्ट देखरेख. पारदर्शक निधी.',
    arch_tag_projects: 'सत्यापित कामे.',
    arch_tag_impact: 'थेट प्रभाव.',
    arch_col1_heading: 'पुरावा आणि गैरव्यवहार तपासणी',
    arch_col2_heading: 'एआय जोखीम मॉडेल',
    arch_col3_heading: 'संवादात्मक डॅशबोर्ड व व्हॉइस एआय',
    arch_btn_evidence: 'पुरावा प्रयोगशाळा उघडा',
    arch_btn_dossier: 'नमुना डॉसियर पहा',
  },

  'ta-IN': {
    brand_title: 'எம்பி நிதி நுண்ணறிவு',
    brand_tag: 'புள்ளியியல் அமைச்சகம் e-SAKSHI அடுக்கு',
    brand_sub: 'புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம் • இந்திய அரசு',
    search_placeholder: 'திட்ட எண், மாவட்டம், ஒப்பந்தக்காரரைத் தேடுக...',
    role_admin: 'மத்திய தணிக்கையாளர்',
    role_district: 'மாவட்ட ஆட்சியர் (DM)',
    role_citizen: 'குடிமக்கள் தளம்',
    role_persona: 'செயலில் உள்ள நிர்வாகப் பங்கு',
    role_admin_sub: 'தேசிய மேற்பார்வை & சிண்டிகேட் ஆய்வு',
    role_district_sub: 'SLA எச்சரிக்கைகள் & புகைப்பட சரிபார்ப்பு',
    role_citizen_sub: 'திட்ட தேடல் & குறைதீர்ப்பு',
    indic_btn: 'சர்வம் AI',
    voice_briefing_btn: 'குரல் AI',
    sign_out: 'வெளியேறு',
    sec_profile: 'பாதுகாப்பு & சுயவிவரம்',
    public_portal: 'பொது வெளிப்படைத்தன்மை தளம்',

    suite_admin: 'தேசிய கட்டளை மையம்',
    suite_district: 'மாவட்ட ஆட்சியர் கட்டுப்பாட்டு மையம்',
    suite_citizen: 'குடிமக்கள் வழிகாட்டி',
    nav_exec_dashboard: 'நிர்வாக டாஷ்போர்டு',
    nav_analytics: 'நுண்ணறிவு பகுப்பாய்வு',
    nav_risk_map: 'தேசிய இடர் வரைபடம்',
    nav_high_risk: 'அதி-இடர் தணிக்கை வரிசை',
    nav_cartel_matrix: 'ஒப்பந்தக்காரர் கூட்டு ஆதிக்கம்',
    nav_all_works: 'அனைத்து அங்கீகரிக்கப்பட்ட பணிகள்',
    nav_evidence_lab: 'AI தடயவியல் சான்று ஆய்வகம்',
    nav_sla: 'காலக்கெடு மீறல் எச்சரிக்கைகள்',
    nav_district_overview: 'மாவட்ட மேலோட்டம்',
    nav_pending_sanctions: 'நிலுவையில் உள்ள ஒப்புதல்கள்',
    nav_sla_alerts: 'காலக்கெடு அபாய எச்சரிக்கைகள்',
    nav_pre_screening: 'AI முதற்கட்ட ஆய்வு',
    nav_photo_val: 'புகைப்பட உண்மைத்தன்மை சரிபார்ப்பு',
    nav_constituency_works: 'தொகுதி வளர்ச்சிப் பணிகள்',
    nav_public_home: 'பொது விழிப்புணர்வு தளம்',
    nav_geo_explorer: 'புவியியல் பணி ஆய்வாளர்',
    nav_search_works: 'உள்ளூர் பணிகளைத் தேடுக',
    nav_submit_grievance: 'குடிமக்கள் புகாரைப் பதிவுசெய்க',

    kpi_total_projects: 'மொத்த அங்கீகரிக்கப்பட்ட பணிகள்',
    kpi_total_projects_sub: 'அனைத்து 28 மாநிலங்கள் & யூனியன் பிரதேசங்கள்',
    kpi_total_funds: 'ஒதுக்கப்பட்ட மொத்த நிதி',
    kpi_total_funds_sub: 'நிதியாண்டு 2025-26-ல் வழங்கப்பட்டது',
    kpi_ai_monitored: 'AI தொடர் கண்காணிப்பு',
    kpi_ai_monitored_sub: '95.5% தரவு பாதுகாப்பு',
    kpi_anomalies: 'கண்டறியப்பட்ட முறைகேடுகள்',
    kpi_anomalies_sub: 'செலவு, புகைப்படம் & ஏகபோக ஆதிக்கம்',
    kpi_high_risk: 'அதி-இடர் திட்டங்கள்',
    kpi_high_risk_sub: 'உடனடி கள ஆய்வு தேவை',
    kpi_sla_risk: 'காலக்கெடு மீறல் அபாயம்',
    kpi_sla_risk_sub: '12 அவசர நிலைகள் (<48 மணி நேரம்)',

    arch_title: 'எம்பிஎல்ஏடி சென்டினல் கட்டமைப்பு மற்றும் நுண்ணறிவு இயந்திரம்',
    arch_subtitle: 'முத்தூண் தணிக்கை கட்டமைப்பு: AI பகுப்பாய்வு, கணித இடர் மதிப்பீடு, மற்றும் புவியியல் இடைமுகம்',
    arch_col1_title: 'தூண் 1: AI பகுப்பாய்வு இயந்திரங்கள் (மூளை)',
    arch_col1_sub: 'மனித தணிக்கைக்குப் பதிலாக தானியங்கி கணினி பார்வை மற்றும் வரைபட ML',
    arch_col1_f1_title: 'நகல் புகைப்படக் கண்டறிதல் (OpenCV dHash)',
    arch_col1_f1_desc: '64-பிட் dHash மூலம் பல்வேறு மாவட்ட புகைப்படங்களை ஒப்பிட்டு பழைய படங்களின் மறுபயன்பாட்டைத் தடுக்கிறது.',
    arch_col1_f2_title: 'ஒப்பந்தக்காரர் கூட்டு ஆய்வு (NetworkX)',
    arch_col1_f2_desc: 'டெண்டர் வரைபடம் உருவாக்கி ஹெர்பிண்டால் குறியீட்டின் (HHI) மூலம் ஏகபோக சந்தை அபாயத்தை வெளிப்படுத்துகிறது.',
    arch_col1_f3_title: 'புவியியல் மற்றும் தட்பவெப்ப இயல்பாக்கம்',
    arch_col1_f3_desc: 'மலை மற்றும் மழைக்காலப் பகுதிகளின் தாமதங்களை நியாயமாக மதிப்பிடுகிறது.',

    arch_col2_title: 'தூண் 2: முக்கிய செயலாக்க இயந்திரம் (கணித மாதிரி)',
    arch_col2_sub: 'துல்லியமான இடர் சூத்திரம் மற்றும் அதிவேக FastAPI சேவைகள்',
    arch_col2_f1_title: 'கணித இடர் சூத்திரம்',
    arch_col2_f1_desc: 'R = 0.35F + 0.25T + 0.20I + 0.20C சூத்திரத்தின் அடிப்படையில் 0-100 வரம்பில் மதிப்பெண் வழங்கப்படுகிறது.',
    arch_col2_f2_title: 'முன்னுரிமை பிரிவுகள்',
    arch_col2_f2_desc: 'திட்டங்களை 🔴 அதி-இடர் (>70), 🟡 எச்சரிக்கை (40-69), மற்றும் 🟢 பாதுகாப்பானது (<40) எனப் பிரிக்கிறது.',
    arch_col2_f3_title: 'நேரடி REST API (FastAPI)',
    arch_col2_f3_desc: 'GET /projects, POST /analyze-image, மற்றும் GET /cartel-graphSwagger ஆவணங்களுடன் செயல்படுகின்றன.',

    arch_col3_title: 'தூண் 3: ஊடாடும் டாஷ்போர்டு (இடைமுகம்)',
    arch_col3_sub: 'GIS வரைபடங்கள், ஸ்லைடு-ஓவர் தணிக்கை பேனல்கள், மற்றும் சர்வம் குரல் AI',
    arch_col3_f1_title: 'புவியியல் மாவட்ட வரைபடம் (Leaflet.js)',
    arch_col3_f1_desc: 'வண்ணக் குறியீட்டுடன் நிதிப் பயன்பாடு மற்றும் பிராந்திய இடர்களைக் காட்டும் வரைபடம்.',
    arch_col3_f2_title: 'விரிவான ஸ்லைடு-ஓவர் தணிக்கைப் பேனல்',
    arch_col3_f2_desc: 'ஒவ்வொரு திட்டத்தின் செலவு, காலக்கெடு, சான்றுப் படங்கள் மற்றும் AI எச்சரிக்கைகளைக் காட்டுகிறது.',
    arch_col3_f3_title: 'சர்வம் AI குரல் நுண்ணறிவு',
    arch_col3_f3_desc: 'தமிழில் குரல் அறிக்கை (TTS) மற்றும் கிராமப்புற குடிமக்களுக்கான குரல்வழிப் புகார் பதிவு.',

    judge_title: 'கட்டமைப்பு பலவீனங்கள் மற்றும் தீர்வுகள்',
    judge_sub: 'போலி GPS, மனித லஞ்சம், மற்றும் போலியான புகைப்படங்களுக்கு எதிரான பாதுகாப்பு உத்திகள்',
    judge_d1_title: '1. போலி புவிக்குறியீடு சரிபார்ப்பு (GPS Spoofing)',
    judge_d1_desc: 'செல்போன் டவர் ஐடி மற்றும் இணைய ஐபி முகவரியுடன் முத்தரப்பு சரிபார்ப்பு.',
    judge_d2_title: '2. மனித லஞ்சத் தடுப்பு (Bribery Prevention)',
    judge_d2_desc: 'இரு அதிகாரிகளின் டிஜிட்டல் கையொப்பம் (e-Sign) இன்றி எச்சரிக்கைகளை நீக்க முடியாது.',
    judge_d3_title: '3. AI உருவாக்கிய போலி புகைப்படங்கள் (Deepfake)',
    judge_d3_desc: 'FFT ஸ்பெக்ட்ரல் பகுப்பாய்வு மூலம் செயற்கை பிக்சல் முரண்பாடுகளை உடனடியாகக் கண்டறிகிறது.',
    judge_d4_title: '4. மலை மற்றும் தொலைதூரப் பகுதிகளின் சார்புத் தடுப்பு',
    judge_d4_desc: 'புவியியல் சிரமங்களை கணக்கில் கொண்டு பாரபட்சமற்ற தணிக்கையை உறுதிசெய்கிறது.',

    table_work_id: 'பணி எண்',
    table_desc_constituency: 'விவரம் & தொகுதி',
    table_sanction_value: 'ஒதுக்கப்பட்ட தொகை',
    table_composite_risk: 'இடர் மதிப்பீடு',
    table_status: 'தணிக்கை நிலை',
    table_actions: 'நடவடிக்கை',
    btn_audit: 'ஆவணத் தணிக்கை',
    btn_export: 'அறிக்கை பதிவிறக்கம்',
    btn_refresh: 'தரவை புதுப்பிக்கவும்',
    filter_all_states: 'அனைத்து மாநிலங்கள்',
    filter_risk_level: 'அனைத்து இடர் நிலைகள்',
    footer_text: 'எம்பி நிதி AI கண்காணிப்பு — புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம் (MoSPI) • இந்திய அரசு',
    footer_sec: 'வரம்பிற்குட்பட்ட அரசு தணிக்கை அணுகல் • பூஜ்ஜிய நிதி கசிவு நோக்கம்',

    // Home Page Translations
    home_nav_home: 'முகப்பு',
    home_nav_methodology: 'செயல்முறை மற்றும் கோட்பாடுகள்',
    home_nav_about: 'திட்டம் பற்றி',
    home_nav_contact: 'தொடர்பு',
    home_hero_title: 'ஸ்கீம் கார்ட்: உள்ளூர் முன்னுரிமைகளிலிருந்து தேசிய வளர்ச்சி',
    home_hero_sub: 'அனைத்து 543 மக்களவைத் தொகுதிகளிலும் பொது வளர்ச்சிச் சொத்துக்களைப் பாதுகாக்கும் அல்காரிதம் கண்காணிப்பு, PFMS நிதி கண்காணிப்பு மற்றும் படத் தடயவியல்.',
    btn_district_cmd: 'மாவட்ட கட்டளை மையம்',
    home_box_guidelines: 'வழிகாட்டுதல்கள் & சட்டங்கள்',
    home_box_guidelines_sub: '2023 திருத்தப்பட்ட நெறிமுறை',
    home_box_voice: 'குரல்வழி AI உதவி',
    home_box_voice_sub: '8 இந்திய மொழிகள்',
    home_box_citizen: 'குடிமக்கள் கோரிக்கை',
    home_box_citizen_sub: 'உள்ளூர் பகுதி முன்மொழிவு',
    home_box_audit: 'AI தணிக்கை கோப்பு',
    home_box_audit_sub: 'குறிக்கப்பட்ட நந்தூர்பார்',
    home_ticker_badge: 'நேரடி கண்காணிப்பு',
    home_ticker_strong: 'MoSPI e-SAKSHI 2.0 எச்சரிக்கை:',
    home_ticker_desc: 'அனைத்து 543 மக்களவைத் தொகுதிகளிலும் தீவிர கண்காணிப்பு • ₹83,336.67 கோடி நிதி தொடர் ஆய்வு • நகல் புகைப்படங்கள் காரணமாக நந்தூர்பார் திட்டம் 87% அபாயத்தில் • TSA நேரடி நிதி விடுவிப்பு முறை.',
    home_kpi_heading: 'தேசிய வளர்ச்சி குறிகாட்டிகள் & நிதி ஓட்டம்',
    home_kpi_sub: 'திருத்தப்பட்ட TSA நிதி நடைமுறையின் கீழ் மாண்புமிகு எம்பிக்களால் பரிந்துரைக்கப்பட்ட பணிகளின் நேரடி புள்ளிவிவரங்கள்',
    kpi_tab_statutory: 'சட்டபூர்வ e-SAKSHI பார்வை',
    kpi_tab_vigilance: 'AI விழிப்புணர்வு அடுக்கு',
    kpi_sabha_lok: 'மக்களவை (543 எம்பிக்கள்)',
    kpi_sabha_rajya: 'மாநிலங்களவை (245 எம்பிக்கள்)',
    kpi_entitlement: 'ஆண்டு உரிமை (FY)',
    kpi_entitlement_sub: 'ஒரு எம்பி / ஆண்டு',
    kpi_tsa_fund: 'TSA ஒருங்கிணைந்த நிதி',
    kpi_tsa_fund_sub: 'செயலில் உள்ள ஒதுக்கீடு',
    kpi_works_rec: 'பரிந்துரைக்கப்பட்ட பணிகள்',
    kpi_works_rec_sub: 'டிஜிட்டல் சமர்ப்பிப்புகள்',
    kpi_works_sanc: 'அங்கீகரிக்கப்பட்ட பணிகள்',
    kpi_works_sanc_sub: 'சாத்தியக்கூறு வெற்றி',
    kpi_works_comp: 'முடிக்கப்பட்ட பணிகள்',
    kpi_works_comp_sub: 'உருவாக்கப்பட்ட & சரிபார்க்கப்பட்ட சொத்துகள்',
    kpi_expenditure: 'மொத்த செலவினம்',
    kpi_expenditure_sub: 'PFMS நிதி வழங்கல்',
    kpi_ai_monitored_title: 'AI கண்காணிப்பு பணிகள்',
    kpi_ai_monitored_desc: '100% ஜியோடேக் அளவீட்டுப் புத்தகங்கள்',
    kpi_anomalies_title: 'சுட்டிக்காட்டப்பட்ட முறைகேடுகள்',
    kpi_anomalies_desc: 'தொடர் கண்காணிப்பு',
    kpi_high_risk_title: 'அதி-இடர் வரிசை',
    kpi_high_risk_desc: 'இடர் மதிப்பீடு > 70',
    kpi_cartels_title: 'கண்டறியப்பட்ட ஏகபோகங்கள்',
    kpi_cartels_desc: 'HHI குறியீடு > 2500',
    kpi_dup_title: 'நகல் புகைப்பட தடுப்பு',
    kpi_dup_desc: 'OpenCV 64-பிட் dHash',
    kpi_hold_title: 'நிறுத்திவைக்கப்பட்ட நிதி',
    kpi_hold_desc: 'மைல்கல் நிறுத்தம்',
    home_how_it_works: 'இது எவ்வாறு செயல்படுகிறது: தொடர் கண்காணிப்பு & நிதிப் பாதுகாப்பு',
    home_about_title: 'ஸ்கீம் கார்ட் பற்றி',
    home_statutory_overview: 'சட்டபூர்வ கண்ணோட்டம்',
    brand_sub_short: 'புள்ளியியல் மற்றும் திட்ட அமலாக்க அமைச்சகம்',
    home_viksit_bharat: 'விக்சித் பாரத் @ 2047 இலக்கு:',
    home_viksit_desc: 'எம்பி நிதித் திட்டம் மூலம் நீடித்த சமுதாய சொத்துக்கள் மற்றும் கிராமப்புற உள்கட்டமைப்பு உருவாக்கப்படுகிறது.',
    arch_main_heading: 'துல்லிய கண்காணிப்பு. வெளிப்படையான நிதி.',
    arch_tag_projects: 'உண்மையான திட்டங்கள்.',
    arch_tag_impact: 'நேரடி தாக்கம்.',
    arch_col1_heading: 'சான்று மற்றும் மோசடி தடுப்பு',
    arch_col2_heading: 'AI இடர் மதிப்பீட்டு மாதிரிகள்',
    arch_col3_heading: 'ஊடாடும் டாஷ்போர்டு மற்றும் குரல் AI',
    arch_btn_evidence: 'சான்று ஆய்வகத்தைத் திறக்குக',
    arch_btn_dossier: 'மாதிரி ஆவணத்தைப் பார்க்க',
  }
};


DICTIONARY['te-IN'] = {
  ...DICTIONARY['hi-IN'],
  home_nav_home: 'హోమ్',
  home_nav_methodology: 'కార్యవిధానం మరియు సూత్రాలు',
  home_nav_about: 'పథకం గురించి',
  home_nav_contact: 'సంప్రదించండి',
  landing_login: 'లాగిన్',
  home_hero_title: 'స్కీమ్ గార్డ్: స్థానిక ప్రాధాన్యతల నుండి జాతీయ అభివృద్ధి వరకు',
  home_hero_sub: 'అన్ని 543 లోక్‌సభ నియోజకవర్గాల్లో అభివృద్ధి ఆస్తుల రక్షణ: అల్గారిథమిక్ నిఘా, రియల్ టైమ్ PFMS ట్రాకింగ్ మరియు ఫోటో ఫోరెన్సిక్స్.',
  btn_district_cmd: 'జిల్లా కమాండ్ ప్రారంభించండి',
  landing_btn_admin: 'MoSPI కేంద్ర కమాండ్ ప్రారంభించండి',
  landing_btn_public: 'ప్రజా పోర్టల్‌ను అన్వేషించండి',
  home_box_guidelines: 'మార్గదర్శకాలు & చట్టాలు',
  home_box_voice: 'వాయిస్ AI సహాయం',
  home_box_citizen: 'పౌర అభ్యర్థన',
  home_box_audit: 'AI ఆడిట్ డాసియర్',
  home_ticker_badge: 'ప్రత్యక్ష నిఘా',
  home_kpi_heading: 'జాతీయ అభివృద్ధి సూచికలు మరియు నిధుల ప్రవాహం',
  home_how_it_works: 'ఇది ఎలా పనిచేస్తుంది: నిరంతర నిఘా & నిధుల రక్షణ',
  home_about_title: 'స్కీమ్ గార్డ్ గురించి',
  home_statutory_overview: 'చట్టబద్ధమైన అవలోకనం',
  kpi_tab_statutory: 'చట్టబద్ధమైన e-SAKSHI వీక్షణ',
  kpi_tab_vigilance: 'AI నిఘా విభాగం',
  kpi_sabha_lok: 'లోక్‌సభ (543 ఎంపీలు)',
  kpi_sabha_rajya: 'రాజ్యసభ (245 ఎంపీలు)',
  kpi_entitlement: 'వార్షిక అర్హత (FY)',
  kpi_tsa_fund: 'TSA సంయుక్త నిధి',
  kpi_works_rec: 'సిఫార్సు చేయబడిన పనులు',
  kpi_works_sanc: 'మంజూరైన పనులు',
  kpi_works_comp: 'పూర్తయిన పనులు',
  kpi_expenditure: 'మొత్తం ఖర్చు',
  kpi_ai_monitored_title: 'AI పర్యవేక్షణ పనులు',
  kpi_anomalies_title: 'గుర్తించబడిన లోపాలు',
  kpi_high_risk_title: 'అధిక ప్రమాద జాబితా',
  kpi_cartels_title: 'కాంట్రాక్టర్ కార్టెల్స్',
  kpi_dup_title: 'నకిలీ ఫోటో గుర్తింపు',
  kpi_hold_title: 'నిలిపివేసిన నిధులు',
  arch_main_heading: 'స్మార్ట్ పర్యవేక్షణ. పారదర్శక నిధులు.',
  arch_col1_heading: 'సాక్ష్యం & మోసం నివారణ'
};

DICTIONARY['bn-IN'] = {
  ...DICTIONARY['hi-IN'],
  home_nav_home: 'হোম',
  home_nav_methodology: 'কার্যপদ্ধতি ও নীতি',
  home_nav_about: 'প্রকল্প সম্পর্কে',
  home_nav_contact: 'যোগাযোগ',
  landing_login: 'লগইন',
  home_hero_title: 'স্কিম গার্ড: স্থানীয় অগ্রাধিকার থেকে জাতীয় উন্নয়ন',
  home_hero_sub: 'সমস্ত ৫৪৩টি লোকসভা কেন্দ্রে উন্নয়নমূলক সম্পদের সুরক্ষায় অ্যালগরিদমিক সতর্কতা, রিয়েল-টাইম PFMS ট্র্যাকিং এবং ইমেজ ফরেনসিক।',
  btn_district_cmd: 'জেলা কমান্ড শুরু করুন',
  landing_btn_admin: 'MoSPI কেন্দ্রীয় কমান্ড শুরু করুন',
  landing_btn_public: 'পাবলিক পোর্টাল দেখুন',
  home_box_guidelines: 'নির্দেশিকা ও আইন',
  home_box_voice: 'ভয়েস এআই সহায়তা',
  home_box_citizen: 'নাগরিক অনুরোধ',
  home_box_audit: 'এআই অডিট ডসিয়ার',
  home_ticker_badge: 'লাইভ নজরদারি',
  home_kpi_heading: 'জাতীয় উন্নয়ন সূচক ও তহবিল প্রবাহ',
  home_how_it_works: 'এটি কীভাবে কাজ করে: অবিচ্ছিন্ন নজরদারি ও তহবিল সুরক্ষা',
  home_about_title: 'স্কিম গার্ড সম্পর্কে',
  home_statutory_overview: 'সংবিধিবদ্ধ ওভারভিউ',
  kpi_tab_statutory: 'সংবিধিবদ্ধ ই-সাক্ষী দৃশ্য',
  kpi_tab_vigilance: 'এআই নজরদারি স্তর',
  kpi_sabha_lok: 'লোকসভা (৫৪৩ সাংসদ)',
  kpi_sabha_rajya: 'রাজ্যসভা (২৪৫ সাংসদ)',
  kpi_entitlement: 'বার্ষিক বরাদ্দ (FY)',
  kpi_tsa_fund: 'TSA সমন্বিত তহবিল',
  kpi_works_rec: 'সুপারিশকৃত কাজ',
  kpi_works_sanc: 'অনুমোদিত কাজ',
  kpi_works_comp: 'সম্পন্ন কাজ',
  kpi_expenditure: 'মোট ব্যয়',
  kpi_ai_monitored_title: 'এআই নজরদারি কাজ',
  kpi_anomalies_title: 'চিহ্নিত অনিয়ম',
  kpi_high_risk_title: 'উচ্চ ঝুঁকি সারি',
  kpi_cartels_title: 'ঠিকাদার কার্টেল',
  kpi_dup_title: 'ডুপ্লিকেট ছবি সনাক্তকরণ',
  kpi_hold_title: 'স্থগিত তহবিল',
  arch_main_heading: 'স্মার্ট মনিটরিং। স্বচ্ছ তহবিল।',
  arch_col1_heading: 'প্রমাণ ও জালিয়াতি প্রতিরোধ'
};

DICTIONARY['gu-IN'] = {
  ...DICTIONARY['hi-IN'],
  home_nav_home: 'હોમ',
  home_nav_methodology: 'કાર્યપદ્ધતિ અને સિદ્ધાંતો',
  home_nav_about: 'યોજના વિશે',
  home_nav_contact: 'સંપર્ક',
  landing_login: 'લૉગિન',
  home_hero_title: 'સ્કીમ ગાર્ડ: સ્થાનિક પ્રાથમિકતાઓથી રાષ્ટ્રીય વિકાસ',
  home_hero_sub: 'તમામ 543 લોકસભા મતવિસ્તારોમાં જાહેર વિકાસ અસ્કયામતોનું રક્ષણ: એલ્ગોરિધમિક સતર્કતા, વાસ્તવિક સમય PFMS ટ્રેકિંગ અને ફોટો ફોરેન્સિક્સ.',
  btn_district_cmd: 'જિલ્લા કમાન્ડ શરૂ કરો',
  landing_btn_admin: 'MoSPI સેન્ટ્રલ કમાન્ડ શરૂ કરો',
  landing_btn_public: 'પબ્લિક પોર્ટલ જુઓ',
  home_box_guidelines: 'માર્ગદર્શિકા અને કાયદા',
  home_box_voice: 'વૉઇસ AI સહાય',
  home_box_citizen: 'નાગરિક વિનંતી',
  home_box_audit: 'AI ઓડિટ ડોઝિયર',
  home_ticker_badge: 'લાઈવ સર્વેલન્સ',
  home_kpi_heading: 'રાષ્ટ્રીય વિકાસ સૂચકાંકો અને ફંડ પ્રવાહ',
  home_how_it_works: 'તે કેવી રીતે કાર્ય કરે છે: સતત સતર્કતા અને જાહેર ભંડોળ સુરક્ષા',
  home_about_title: 'સ્કીમ ગાર્ડ વિશે',
  home_statutory_overview: 'વૈધાનિક વિહંગાવલોકન',
  kpi_tab_statutory: 'વૈધાનિક e-SAKSHI દૃશ્ય',
  kpi_tab_vigilance: 'AI વિજિલન્સ લેયર',
  kpi_sabha_lok: 'લોકસભા (543 સાંસદો)',
  kpi_sabha_rajya: 'રાજ્યસભા (245 સાંસદો)',
  kpi_entitlement: 'વાર્ષિક પાત્રતા (FY)',
  kpi_tsa_fund: 'TSA સંચિત ફંડ',
  kpi_works_rec: 'ભલામણ કરેલ કામો',
  kpi_works_sanc: 'મંજૂર થયેલા કામો',
  kpi_works_comp: 'પૂર્ણ થયેલ કામો',
  kpi_expenditure: 'કુલ ખર્ચ',
  kpi_ai_monitored_title: 'AI મોનિટર કરેલ કામો',
  kpi_anomalies_title: 'ઓળખાયેલ વિસંગતતાઓ',
  kpi_high_risk_title: 'ઉચ્ચ જોખમ કતાર',
  kpi_cartels_title: 'કોન્ટ્રાક્ટર કાર્ટેલ',
  kpi_dup_title: 'ડુપ્લિકેટ ફોટો ડિટેક્શન',
  kpi_hold_title: 'સ્થગિત ભંડોળ',
  arch_main_heading: 'સ્માર્ટ મોનિટરિંગ. પારદર્શક ભંડોળ.',
  arch_col1_heading: 'પુરાવા અને છેતરપિંડી તપાસ'
};

DICTIONARY['kn-IN'] = {
  ...DICTIONARY['hi-IN'],
  home_nav_home: 'ಮುಖಪುಟ',
  home_nav_methodology: 'ಕಾರ್ಯವಿಧಾನ ಮತ್ತು ತತ್ವಗಳು',
  home_nav_about: 'ಯೋಜನೆಯ ಬಗ್ಗೆ',
  home_nav_contact: 'ಸಂಪರ್ಕಿಸಿ',
  landing_login: 'ಲಾಗಿನ್',
  home_hero_title: 'ಸ್ಕೀಮ್ ಗಾರ್ಡ್: ಸ್ಥಳೀಯ ಆದ್ಯತೆಗಳಿಂದ ರಾಷ್ಟ್ರೀಯ ಅಭಿವೃದ್ಧಿ',
  home_hero_sub: 'ಎಲ್ಲಾ 543 ಲೋಕಸಭಾ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಸಾರ್ವಜನಿಕ ಅಭಿವೃದ್ಧಿ ಆಸ್ತಿಗಳನ್ನು ರಕ್ಷಿಸುವ ಅಲ್ಗಾರಿದಮಿಕ್ ಜಾಗರೂಕತೆ, PFMS ರಿಯಲ್-ಟೈಮ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ಇಮೇಜ್ ಫೊರೆನ್ಸಿಕ್ಸ್.',
  btn_district_cmd: 'ಜಿಲ್ಲಾ ಕಮಾಂಡ್ ಪ್ರಾರಂಭಿಸಿ',
  landing_btn_admin: 'MoSPI ಕೇಂದ್ರ ಕಮಾಂಡ್ ಪ್ರಾರಂಭಿಸಿ',
  landing_btn_public: 'ಸಾರ್ವಜನಿಕ ಪೋರ್ಟಲ್ ವೀಕ್ಷಿಸಿ',
  home_box_guidelines: 'ಮಾರ್ಗಸೂಚಿಗಳು ಮತ್ತು ಕಾಯಿದೆಗಳು',
  home_box_voice: 'ಧ್ವನಿ AI ಸಹಾಯ',
  home_box_citizen: 'ನಾಗರಿಕ ವಿನಂತಿ',
  home_box_audit: 'AI ಆಡಿಟ್ ಡಾಕ್ಯುಮೆಂಟ್',
  home_ticker_badge: 'ಲೈವ್ ಕಣ್ಗಾವಲು',
  home_kpi_heading: 'ರಾಷ್ಟ್ರೀಯ ಅಭಿವೃದ್ಧಿ ಸೂಚಕಗಳು ಮತ್ತು ನಿಧಿ ಹರಿವು',
  home_how_it_works: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ: ನಿರಂತರ ಜಾಗರೂಕತೆ ಮತ್ತು ನಿಧಿ ರಕ್ಷಣೆ',
  home_about_title: 'ಸ್ಕೀಮ್ ಗಾರ್ಡ್ ಬಗ್ಗೆ',
  home_statutory_overview: 'ಶಾಸನಬದ್ಧ ಅವಲೋಕನ',
  kpi_tab_statutory: 'ಶಾಸನಬದ್ಧ e-SAKSHI ನೋಟ',
  kpi_tab_vigilance: 'AI ಜಾಗರೂಕತಾ ಪದರ',
  kpi_sabha_lok: 'ಲೋಕಸಭೆ (543 ಸಂಸದರು)',
  kpi_sabha_rajya: 'ರಾಜ್ಯಸಭೆ (245 ಸಂಸದರು)',
  kpi_entitlement: 'ವಾರ್ಷಿಕ ಹಕ್ಕು (FY)',
  kpi_tsa_fund: 'TSA ಸಂಚಿತ ನಿಧಿ',
  kpi_works_rec: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕಾಮಗಾರಿಗಳು',
  kpi_works_sanc: 'ಮಂಜೂರಾದ ಕಾಮಗಾರಿಗಳು',
  kpi_works_comp: 'ಪೂರ್ಣಗೊಂಡ ಕಾಮಗಾರಿಗಳು',
  kpi_expenditure: 'ಒಟ್ಟು ವೆಚ್ಚ',
  kpi_ai_monitored_title: 'AI ಮೇಲ್ವಿಚಾರಣಾ ಕಾಮಗಾರಿಗಳು',
  kpi_anomalies_title: 'ಪತ್ತೆಯಾದ ಅಕ್ರಮಗಳು',
  kpi_high_risk_title: 'ಹೆಚ್ಚಿನ ಅಪಾಯದ ಸರದಿ',
  kpi_cartels_title: 'ಗುತ್ತಿಗೆದಾರರ ಕಾರ್ಟೆಲ್',
  kpi_dup_title: 'ನಕಲಿ ಫೋಟೋ ಪತ್ತೆ',
  kpi_hold_title: 'ತಡೆಹಿಡಿಯಲಾದ ನಿಧಿಗಳು',
  arch_main_heading: 'ಸ್ಮಾರ್ಟ್ ಮೇಲ್ವಿಚಾರಣೆ. ಪಾರದರ್ಶಕ ನಿಧಿ.',
  arch_col1_heading: 'ಪುರಾವೆ ಮತ್ತು ವಂಚನೆ ತಡೆಗಟ್ಟುವಿಕೆ'
};

export const CARTEL_DICTIONARY = {
  'en-IN': {
    cartel_matrix_title: 'CARTEL & MONOPOLY MATRIX',
    cartel_matrix_sub: 'Procurement Syndicate Forensic Graph • Herfindahl-Hirschman Index (HHI) Analysis',
    cartel_export_dossier: 'Export Forensic Dossier',
    cartel_filter_links: 'Filter Links:',
    cartel_all_links: 'All Links',
    cartel_roc_ownership: 'ROC Ownership',
    cartel_cover_bids: 'Cover Bids',
    cartel_tender_awards: 'Tender Awards',
    cartel_interactive_topology: 'Interactive Network Topology (Director ➔ Vendors ➔ Sanctioned Works)',
    cartel_syndicate_map: 'Interactive Syndicate Map',
    cartel_map_hint: 'Select any node or card below to highlight syndicate linkages and review forensic intelligence dossier.',
    cartel_public_works_heading: 'Public Works Under Cartel Monopoly',
    cartel_dossier_title: 'Entity Intelligence Dossier',
    cartel_dossier_empty: 'Select any node in the graph to inspect forensic linkages, MCA filings, and tender collusion metrics.',
    cartel_flagged_entity: 'Flagged Entity Profile',
    cartel_forensic_evidence: 'Procurement & Collusion Forensic Evidence',
    cartel_cover_bidders: 'Identified Cover / Shadow Bidders',
    cartel_director_interlocking: 'Director Interlocking & MCA Cross-Holdings',
    cartel_vigilance_rec: 'Dispatched Vigilance Recommendation',
    cartel_btn_dossier: 'Download Official CBI/CVC Forensic Dossier',
    cartel_btn_freeze: 'Freeze Treasury Disbursal (Rule 239)',
    cartel_connected_works: 'Connected Public Works',
    cartel_inspect_node: 'Inspect Node',
    cartel_active_syndicate: 'Active Syndicate',
    cartel_critical_risk: 'Critical Risk',
    cartel_cover_bidding: 'Cover Bidding',
    cartel_hhi_label: 'HHI Concentration',
    cartel_bids_won: 'Tenders Won',
    home_statutory_view: 'Statutory View',
    home_ai_vigilance: 'AI Vigilance',
    home_lok_sabha: 'Lok Sabha (543 MPs)',
    home_rajya_sabha: 'Rajya Sabha (245 MPs)',
    home_guidelines_title: 'Guidelines & Acts',
    home_guidelines_sub: '2023 Protocol',
    home_voice_title: 'Voice AI Assistant',
    home_voice_sub: '8 Indic Languages',
    home_citizen_title: 'Citizen Request',
    home_citizen_sub: 'Area Proposal',
    home_audit_title: 'AI Audit Dossier',
    home_audit_sub: 'Flagged Works',
  },
  'hi-IN': {
    cartel_matrix_title: 'ठेकेदार सिंडिकेट एवं कार्टेल मैट्रिक्स',
    cartel_matrix_sub: 'खरीद सिंडिकेट फोरेंसिक ग्राफ • हर्फ़िन्डाहल-हर्षमैन सूचकांक (HHI) विश्लेषण',
    cartel_export_dossier: 'फोरेंसिक डोजियर निर्यात करें',
    cartel_filter_links: 'लिंक फिल्टर करें:',
    cartel_all_links: 'सभी संबंध (All)',
    cartel_roc_ownership: 'ROC स्वामित्व संबंध',
    cartel_cover_bids: 'कवर / छद्म बोलियां',
    cartel_tender_awards: 'आवंटित निविदाएं',
    cartel_interactive_topology: 'इंटरैक्टिव नेटवर्क टोपोलॉजी (निदेशक ➔ ठेकेदार ➔ स्वीकृत कार्य)',
    cartel_syndicate_map: 'इंटरैक्टिव सिंडिकेट मानचित्र',
    cartel_map_hint: 'सिंडिकेट संबंधों को हाइलाइट करने और फोरेंसिक जांच रिपोर्ट देखने के लिए किसी भी नोड या कार्ड पर क्लिक करें।',
    cartel_public_works_heading: 'सिंडिकेट एकाधिकार के अंतर्गत सार्वजनिक कार्य',
    cartel_dossier_title: 'संस्था फोरेंसिक खुफिया डोजियर',
    cartel_dossier_empty: 'फोरेंसिक संबंध, कंपनी मंत्रालय (MCA) फाइलिंग और मिलीभगत मेट्रिक्स देखने के लिए ग्राफ में किसी नोड का चयन करें।',
    cartel_flagged_entity: 'चिह्नित संस्था प्रोफ़ाइल',
    cartel_forensic_evidence: 'खरीद एवं मिलीभगत फोरेंसिक साक्ष्य',
    cartel_cover_bidders: 'पहचाने गए छद्म / डमी बोलीदाता',
    cartel_director_interlocking: 'निदेशक अंतर्संबंध एवं MCA क्रॉस-शेयरधारिता',
    cartel_vigilance_rec: 'प्रेषित सतर्कता सिफारिश एवं कार्यवाही',
    cartel_btn_dossier: 'आधिकारिक CBI/CVC फोरेंसिक डोजियर डाउनलोड करें',
    cartel_btn_freeze: 'राजकोषीय भुगतान रोकें (नियम 239)',
    cartel_connected_works: 'संबद्ध सार्वजनिक विकास कार्य',
    cartel_inspect_node: 'जांचें (Inspect)',
    cartel_active_syndicate: 'सक्रिय सिंडिकेट',
    cartel_critical_risk: 'अत्यधिक जोखिम (Critical)',
    cartel_cover_bidding: 'कवर बोली (Cover Bidding)',
    cartel_hhi_label: 'HHI संकेंद्रण',
    cartel_bids_won: 'जीती गई निविदाएं',
    home_statutory_view: 'संवैधानिक दृश्य',
    home_ai_vigilance: 'एआई सतर्कता',
    home_lok_sabha: 'लोकसभा (543 सांसद)',
    home_rajya_sabha: 'राज्यसभा (245 सांसद)',
    home_guidelines_title: 'दिशानिर्देश एवं अधिनियम',
    home_guidelines_sub: '2023 संशोधित प्रोटोकॉल',
    home_voice_title: 'ध्वनि AI सहायक',
    home_voice_sub: '8 भारतीय भाषाएं',
    home_citizen_title: 'नागरिक अनुरोध',
    home_citizen_sub: 'क्षेत्रीय प्रस्ताव',
    home_audit_title: 'एआई ऑडिट डोजियर',
    home_audit_sub: 'चिह्नित कार्य (नंदुरबार)',
  },
  'mr-IN': {
    cartel_matrix_title: 'कंत्राटदार कार्टेल आणि मक्तेदारी मॅट्रिक्स',
    cartel_matrix_sub: 'निविदा सिंडिकेट फॉरेन्सिक आलेख • हर्फ़िन्डाहल-हर्षमन निर्देशांक (HHI) विश्लेषण',
    cartel_export_dossier: 'फॉरेन्सिक अहवाल डाउनलोड करा',
    cartel_filter_links: 'दुवे फिल्टर करा:',
    cartel_all_links: 'सर्व दुवे',
    cartel_roc_ownership: 'ROC मालकी दुवे',
    cartel_cover_bids: 'डमी कव्हर बोली',
    cartel_tender_awards: 'मंजूर निविदा',
    cartel_interactive_topology: 'नेटवर्क टोपोलॉजी (संचालक ➔ कंत्राटदार ➔ मंजूर कामे)',
    cartel_syndicate_map: 'सिंडिकेट नकाशा',
    cartel_map_hint: 'सिंडिकेट दुवे पाहण्यासाठी आणि फॉरेन्सिक तपास अहवाल तपासण्यासाठी कोणत्याही कार्डवर क्लिक करा.',
    cartel_public_works_heading: 'कंत्राटदार मक्तेदारीखालील सार्वजनिक विकास कामे',
    cartel_dossier_title: 'संस्था फॉरेन्सिक गुप्तवार्ता अहवाल',
    cartel_dossier_empty: 'फॉरेन्सिक दुवे आणि निविदा मिलीभगत मेट्रिक्स तपासण्यासाठी आलेखातील कोणत्याही नोडवर क्लिक करा.',
    cartel_flagged_entity: 'चिन्हांकित संस्था प्रोफाइल',
    cartel_forensic_evidence: 'खरेदी आणि मिलीभगत फॉरेन्सिक पुरावे',
    cartel_cover_bidders: 'शोधून काढलेले डमी कव्हर बोलीदार',
    cartel_director_interlocking: 'संचालक परस्परसंबंध आणि MCA क्रॉस-होल्डिंग्स',
    cartel_vigilance_rec: 'शिफारस केलेली दक्षता कारवाई',
    cartel_btn_dossier: 'अधिकृत CBI/CVC फॉरेन्सिक अहवाल डाउनलोड करा',
    cartel_btn_freeze: 'तिजोरी निधी वितरण स्थगित करा (नियम २३९)',
    cartel_connected_works: 'संबंधित सार्वजनिक कामे',
    cartel_inspect_node: 'तपासा',
    cartel_active_syndicate: 'सक्रिय सिंडिकेट',
    cartel_critical_risk: 'गंभीर धोका',
    cartel_cover_bidding: 'कव्हर बोली',
    cartel_hhi_label: 'HHI संकेंद्रण',
    cartel_bids_won: 'जिंकलेली निविदा',
    home_statutory_view: 'वैधानिक दृश्य',
    home_ai_vigilance: 'एआय दक्षता',
    home_lok_sabha: 'लोकसभा (543 खासदार)',
    home_rajya_sabha: 'राज्यसभा (245 खासदार)',
    home_guidelines_title: 'मार्गदर्शक तत्त्वे व कायदे',
    home_guidelines_sub: '2023 प्रोटोकॉल',
    home_voice_title: 'व्हॉइस AI सहाय्यक',
    home_voice_sub: '8 भारतीय भाषा',
    home_citizen_title: 'नागरिक विनंती',
    home_citizen_sub: 'स्थानिक विकास प्रस्ताव',
    home_audit_title: 'एआय ऑडिट अहवाल',
    home_audit_sub: 'नंदुरबार तपासणी',
  },
  'ta-IN': {
    cartel_matrix_title: 'ஒப்பந்தக்காரர் கூட்டு சந்தை வரைபடம்',
    cartel_matrix_sub: 'கொள்முதல் சிண்டிகேட் தடயவியல் வரைபடம் • HHI பகுப்பாய்வு',
    cartel_export_dossier: 'தடயவியல் கோப்பை பதிவிறக்கு',
    cartel_filter_links: 'இணைப்புகளை வடிகட்டுக:',
    cartel_all_links: 'அனைத்து இணைப்புகள்',
    cartel_roc_ownership: 'ROC உரிமை',
    cartel_cover_bids: 'போலி ஏலங்கள்',
    cartel_tender_awards: 'ஒப்பந்த ஒதுக்கீடு',
    cartel_interactive_topology: 'வலையமைப்பு வரைபடம் (இயக்குனர் ➔ ஒப்பந்தக்காரர்கள் ➔ பணிகள்)',
    cartel_syndicate_map: 'சிண்டிகேட் வரைபடம்',
    cartel_map_hint: 'தடயவியல் உளவுத்துறை கோப்பை மதிப்பாய்வு செய்ய ஏதேனும் முனையைக் கிளிக் செய்யவும்.',
    cartel_public_works_heading: 'கூட்டு சந்தை ஏகபோகத்தின் கீழ் பொதுப் பணிகள்',
    cartel_dossier_title: 'நிறுவன புலனாய்வு ஆவணம்',
    cartel_dossier_empty: 'தடயவியல் இணைப்புகள் மற்றும் ஒப்பந்த கூட்டு மெட்ரிக்குகளை ஆய்வு செய்ய வரைபடத்தில் ஏதேனும் முனையைத் தேர்ந்தெடுக்கவும்.',
    cartel_flagged_entity: 'குறியிடப்பட்ட நிறுவன சுயவிவரம்',
    cartel_forensic_evidence: 'கொள்முதல் மற்றும் கூட்டு தடயவியல் சான்றுகள்',
    cartel_cover_bidders: 'கண்டறியப்பட்ட போலி ஏலதாரர்கள்',
    cartel_director_interlocking: 'இயக்குனர் பரஸ்பர தொடர்புகள் & MCA குறுக்கு பங்குகள்',
    cartel_vigilance_rec: 'அனுப்பப்பட்ட விழிப்புணர்வு பரிந்துரை',
    cartel_btn_dossier: 'அதிகாரப்பூர்வ CBI/CVC தடயவியல் ஆவணத்தை பதிவிறக்குக',
    cartel_btn_freeze: 'கருவூல நிதியை முடக்குக (விதி 239)',
    cartel_connected_works: 'இணைக்கப்பட்ட பொதுப் பணிகள்',
    cartel_inspect_node: 'ஆய்வு செய்',
    cartel_active_syndicate: 'செயலில் உள்ள சிண்டிகேட்',
    cartel_critical_risk: 'கடுமையான அபாயம்',
    cartel_cover_bidding: 'போலி ஏலம்',
    cartel_hhi_label: 'HHI செறிவு',
    cartel_bids_won: 'வென்ற டெண்டர்கள்',
    home_statutory_view: 'சட்டரீதியான பார்வை',
    home_ai_vigilance: 'AI விழிப்புணர்வு',
    home_lok_sabha: 'மக்களவை (543 எம்பிக்கள்)',
    home_rajya_sabha: 'மாநிலங்களவை (245 எம்பிக்கள்)',
    home_guidelines_title: 'வழிகாட்டுதல்கள் மற்றும் சட்டங்கள்',
    home_guidelines_sub: '2023 நெறிமுறை',
    home_voice_title: 'குரல் AI உதவியாளர்',
    home_voice_sub: '8 இந்திய மொழிகள்',
    home_citizen_title: 'குடிமக்கள் கோரிக்கை',
    home_citizen_sub: 'வட்டார திட்டம்',
    home_audit_title: 'AI தணிக்கை ஆவணம்',
    home_audit_sub: 'நந்தூர்பார் ஆய்வு',
  },
  'te-IN': {
    cartel_matrix_title: 'కాంట్రాక్టర్ల సిండికేట్ & కార్టెల్ మ్యాట్రిక్స్',
    cartel_matrix_sub: 'టెండర్ సిండికేట్ ఫోరెన్సిక్ గ్రాఫ్ • HHI విశ్లేషణ',
    cartel_export_dossier: 'ఫోరెన్సిక్ ఫైల్ డౌన్‌లోడ్',
    cartel_filter_links: 'లింకులను ఫిల్టర్ చేయండి:',
    cartel_all_links: 'అన్ని లింకులు',
    cartel_roc_ownership: 'ROC యాజమాన్యం',
    cartel_cover_bids: 'కవర్ బిడ్లు',
    cartel_tender_awards: 'టెండర్ కేటాయింపులు',
    cartel_interactive_topology: 'నెట్‌వర్క్ టోపోలాజీ (డైరెక్టర్ ➔ కాంట్రాక్టర్లు ➔ పనులు)',
    cartel_syndicate_map: 'సిండికేట్ మ్యాప్',
    cartel_map_hint: 'ఫోరెన్సిక్ ఇంటెలిజెన్స్ ఫైల్‌ను సమీక్షించడానికి ఏదైనా నోడ్‌ను ఎంచుకోండి.',
    cartel_public_works_heading: 'కార్టెల్ మోనోపోలీ కింద ప్రజా పనులు',
    cartel_dossier_title: 'సంస్థ ఫోరెన్సిక్ ఇంటెలిజెన్స్ ఫైల్',
    cartel_dossier_empty: 'ఫోరెన్సిక్ సంబంధాలు మరియు టెండర్ కుమ్మక్కు మెట్రిక్‌లను పరిశీలించడానికి గ్రాఫ్‌లోని ఏదైనా నోడ్‌ను ఎంచుకోండి.',
    cartel_flagged_entity: 'గుర్తించబడిన సంస్థ ప్రొఫైల్',
    cartel_forensic_evidence: 'టెండర్ కుమ్మక్కు ఫోరెన్సిక్ ఆధారాలు',
    cartel_cover_bidders: 'గుర్తించబడిన కవర్ / షాడో బిడ్డర్లు',
    cartel_director_interlocking: 'డైరెక్టర్ ఇంటర్‌లాకింగ్ & MCA క్రాస్-హోల్డింగ్స్',
    cartel_vigilance_rec: 'సిఫార్సు చేయబడిన నిఘా చర్య',
    cartel_btn_dossier: 'అధికారిక CBI/CVC ఫోరెన్సిక్ ఫైల్ డౌన్‌లోడ్ చేయండి',
    cartel_btn_freeze: 'ఖజానా నిధులను స్తంభింపజేయండి (నిబంధన 239)',
    cartel_connected_works: 'అనుసంధానించబడిన ప్రజా పనులు',
    cartel_inspect_node: 'పరిశీలించండి',
    cartel_active_syndicate: 'క్రియాశీల సిండికేట్',
    cartel_critical_risk: 'తీవ్రమైన ప్రమాదం',
    cartel_cover_bidding: 'కవర్ బిడ్డింగ్',
    cartel_hhi_label: 'HHI సాంద్రత',
    cartel_bids_won: 'గెలిచిన టెండర్లు',
    home_statutory_view: 'చట్టబద్ధమైన వీక్షణ',
    home_ai_vigilance: 'AI విజిలెన్స్',
    home_lok_sabha: 'లోక్‌సభ (543 ఎంపీలు)',
    home_rajya_sabha: 'రాజ్యసభ (245 ఎంపీలు)',
    home_guidelines_title: 'మార్గదర్శకాలు మరియు చట్టాలు',
    home_guidelines_sub: '2023 ప్రోటోకాల్',
    home_voice_title: 'వాయిస్ AI అసిస్టెంట్',
    home_voice_sub: '8 భారతీయ భాషలు',
    home_citizen_title: 'పౌర అభ్యర్థన',
    home_citizen_sub: 'ప్రాంతీయ ప్రతిపాదన',
    home_audit_title: 'AI ఆడిట్ ఫైల్',
    home_audit_sub: 'నందూర్బార్ నిఘా',
  },
  'bn-IN': {
    cartel_matrix_title: 'ঠিকাদার সিন্ডিকেট ও কার্টেল ম্যাট্রিক্স',
    cartel_matrix_sub: 'সংগ্রহ সিন্ডিকেট ফরেনসিক গ্রাফ • HHI বিশ্লেষণ',
    cartel_export_dossier: 'ফরেনসিক ডসিয়ার এক্সপোর্ট',
    cartel_filter_links: 'লিঙ্ক ফিল্টার করুন:',
    cartel_all_links: 'সমস্ত লিঙ্ক',
    cartel_roc_ownership: 'ROC মালিকানা',
    cartel_cover_bids: 'কভার দরপত্র',
    cartel_tender_awards: 'টেন্ডার বরাদ্দ',
    cartel_interactive_topology: 'নেটওয়ার্ক টপোলজি (পরিচালক ➔ ঠিকাদার ➔ অনুমোদিত কাজ)',
    cartel_syndicate_map: 'সিন্ডিকেট মানচিত্র',
    cartel_map_hint: 'সিন্ডিকেট সংযোগ ও ফরেনসিক গোয়েন্দা ডসিয়ার পর্যালোচনা করতে যেকোনো নোড নির্বাচন করুন।',
    cartel_public_works_heading: 'কার্টেল একচেটিয়া নিয়ন্ত্রণের অধীনে গণপূর্ত কাজ',
    cartel_dossier_title: 'প্রতিষ্ঠান ফরেনসিক গোয়েন্দা ডসিয়ার',
    cartel_dossier_empty: 'ফরেনসিক সংযোগ এবং টেন্ডার যোগসাজশ মেট্রিক্স পরিদর্শন করতে গ্রাফের যেকোনো নোড নির্বাচন করুন।',
    cartel_flagged_entity: 'চিহ্নিত প্রতিষ্ঠান প্রোফাইল',
    cartel_forensic_evidence: 'সংগ্রহ ও যোগসাজশ ফরেনসিক প্রমাণ',
    cartel_cover_bidders: 'চিহ্নিত কভার / ডামি দরদাতারা',
    cartel_director_interlocking: 'পরিচালক আন্তঃসংযোগ ও MCA ক্রস-হোল্ডিংস',
    cartel_vigilance_rec: 'প্রস্তাবিত ভিজিল্যান্স সুপারিশ ও পদক্ষেপ',
    cartel_btn_dossier: 'অফিসিয়াল CBI/CVC ফরেনসিক ডসিয়ার ডাউনলোড করুন',
    cartel_btn_freeze: 'ট্রেজারি অর্থ প্রদান স্থগিত করুন (নিয়ম ২৩৯)',
    cartel_connected_works: 'সংযুক্ত গণপূর্ত কাজ',
    cartel_inspect_node: 'পরিদর্শন করুন',
    cartel_active_syndicate: 'সক্রিয় সিন্ডিকেট',
    cartel_critical_risk: 'মারাত্মক ঝুঁকি',
    cartel_cover_bidding: 'কভার দরপত্র',
    cartel_hhi_label: 'HHI ঘনত্ব',
    cartel_bids_won: 'জয়ী টেন্ডার',
    home_statutory_view: 'সংবিধিবদ্ধ ভিউ',
    home_ai_vigilance: 'এআই নজরদারি',
    home_lok_sabha: 'লোকসভা (৫৪৩ সাংসদ)',
    home_rajya_sabha: 'রাজ্যসভা (২৪৫ সাংসদ)',
    home_guidelines_title: 'নির্দেশিকা ও আইন',
    home_guidelines_sub: '২০২৩ প্রোটোকল',
    home_voice_title: 'ভয়েস AI সহকারী',
    home_voice_sub: '৮টি ভারতীয় ভাষা',
    home_citizen_title: 'নাগরিকের অনুরোধ',
    home_citizen_sub: 'এলাকা উন্নয়ন প্রস্তাব',
    home_audit_title: 'এআই অডিট ডসিয়ার',
    home_audit_sub: 'নন্দুরবার অডিট',
  },
  'gu-IN': {
    cartel_matrix_title: 'કોન્ટ્રાક્ટર કાર્ટેલ અને મોનોપોલી મેટ્રિક્સ',
    cartel_matrix_sub: 'ટેન્ડર સિન્ડિકેટ ફોરેન્સિક ગ્રાફ • HHI વિશ્લેષણ',
    cartel_export_dossier: 'ફોરેન્સિક ડોઝિયર નિકાસ કરો',
    cartel_filter_links: 'લિંક્સ ફિલ્ટર કરો:',
    cartel_all_links: 'તમામ લિંક્સ',
    cartel_roc_ownership: 'ROC માલિકી',
    cartel_cover_bids: 'કવર બિડ્સ',
    cartel_tender_awards: 'ટેન્ડર ફાળવણી',
    cartel_interactive_topology: 'નેટવર્ક ટોપોલોજી (ડિરેક્ટર ➔ કોન્ટ્રાક્ટરો ➔ મંજૂર કામો)',
    cartel_syndicate_map: 'સિન્ડિકેટ નકશો',
    cartel_map_hint: 'સિન્ડિકેટ લિંક્સ જોવા અને ફોરેન્સિક તપાસ રિપોર્ટ જોવા માટે કોઈપણ કાર્ડ પર ક્લિક કરો.',
    cartel_public_works_heading: 'કાર્ટેલ મોનોપોલી હેઠળના જાહેર વિકાસ કામો',
    cartel_dossier_title: 'સંસ્થા ફોરેન્સિક ગુપ્તચર ડોઝિયર',
    cartel_dossier_empty: 'ફોરેન્સિક લિંક્સ અને મિલીભગત મેટ્રિક્સ તપાસવા માટે ગ્રાફમાં કોઈપણ નોડ પસંદ કરો.',
    cartel_flagged_entity: 'ચિહ્નિત સંસ્થા પ્રોફાઇલ',
    cartel_forensic_evidence: 'ટેન્ડર અને મિલીભગત ફોરેન્સિક પુરાવા',
    cartel_cover_bidders: 'ઓળખાયેલ ડમી કવર બિડર્સ',
    cartel_director_interlocking: 'ડિરેક્ટર આંતરસંબંધો અને MCA ક્રોસ-હોલ્ડિંગ્સ',
    cartel_vigilance_rec: 'ભલામણ કરેલ વિજિલન્સ કાર્યવાહી',
    cartel_btn_dossier: 'સત્તાવાર CBI/CVC ફોરેન્સિક ડોઝિયર ડાઉનલોડ કરો',
    cartel_btn_freeze: 'તિજોરી ભંડોળ વિતરણ સ્થગિત કરો (નિયમ ૨૩૯)',
    cartel_connected_works: 'સંકળાયેલ જાહેર કામો',
    cartel_inspect_node: 'તપાસો',
    cartel_active_syndicate: 'સક્રિય સિન્ડિકેટ',
    cartel_critical_risk: 'ગંભીર જોખમ',
    cartel_cover_bidding: 'કવર બિડિંગ',
    cartel_hhi_label: 'HHI એકાગ્રતા',
    cartel_bids_won: 'જીતેલા ટેન્ડર્સ',
    home_statutory_view: 'વૈધાનિક દૃશ્ય',
    home_ai_vigilance: 'AI વિજિલન્સ',
    home_lok_sabha: 'લોકસભા (543 સાંસદો)',
    home_rajya_sabha: 'રાજ્યસભા (245 સાંસદો)',
    home_guidelines_title: 'માર્ગદર્શિકા અને કાયદા',
    home_guidelines_sub: '2023 પ્રોટોકોલ',
    home_voice_title: 'વોઇસ AI સહાયક',
    home_voice_sub: '8 ભારતીય ભાષાઓ',
    home_citizen_title: 'નાગરિક વિનંતી',
    home_citizen_sub: 'વિસ્તાર વિકાસ દરખાસ્ત',
    home_audit_title: 'AI ઓડિટ ડોઝિયર',
    home_audit_sub: 'નંદુરબાર ઓડિટ',
  },
  'kn-IN': {
    cartel_matrix_title: 'ಗುತ್ತಿಗೆದಾರರ ಕಾರ್ಟೆಲ್ ಮತ್ತು ಏಕಸ್ವಾಮ್ಯ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    cartel_matrix_sub: 'ಟೆಂಡರ್ ಸಿಂಡಿಕೇಟ್ ಫೋರೆನ್ಸಿಕ್ ಗ್ರಾಫ್ • HHI ವಿಶ್ಲೇಷಣೆ',
    cartel_export_dossier: 'ಫೋರೆನ್ಸಿಕ್ ದಾಖಲೆ ಡೌನ್‌ಲೋಡ್',
    cartel_filter_links: 'ಲಿಂಕ್‌ಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ:',
    cartel_all_links: 'ಎಲ್ಲಾ ಲಿಂಕ್‌ಗಳು',
    cartel_roc_ownership: 'ROC ಮಾಲೀಕತ್ವ',
    cartel_cover_bids: 'ಕವರ್ ಬಿಡ್‌ಗಳು',
    cartel_tender_awards: 'ಟೆಂಡರ್ ಹಂಚಿಕೆ',
    cartel_interactive_topology: 'ನೆಟ್‌ವರ್ಕ್ ಟೊಪೊಲಾಜಿ (ನಿರ್ದೇಶಕ ➔ ಗುತ್ತಿಗೆದಾರರು ➔ ಮಂಜೂರಾದ ಕಾಮಗಾರಿಗಳು)',
    cartel_syndicate_map: 'ಸಿಂಡಿಕೇಟ್ ನಕ್ಷೆ',
    cartel_map_hint: 'ಫೋರೆನ್ಸಿಕ್ ಗುಪ್ತಚರ ವರದಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ಯಾವುದೇ ನೋಡ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    cartel_public_works_heading: 'ಕಾರ್ಟೆಲ್ ಏಕಸ್ವಾಮ್ಯದ ಅಡಿಯಲ್ಲಿ ಸಾರ್ವಜನಿಕ ಕಾಮಗಾರಿಗಳು',
    cartel_dossier_title: 'ಸಂಸ್ಥೆಯ ಫೋರೆನ್ಸಿಕ್ ಗುಪ್ತಚರ ಕಡತ',
    cartel_dossier_empty: 'ಫೋರೆನ್ಸಿಕ್ ಲಿಂಕ್‌ಗಳು ಮತ್ತು ಟೆಂಡರ್ ಹೊಂದಾಣಿಕೆಯ ಮೆಟ್ರಿಕ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಗ್ರಾಫ್‌ನಲ್ಲಿ ಯಾವುದೇ ನೋಡ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    cartel_flagged_entity: 'ಗುರುತಿಸಲಾದ ಸಂಸ್ಥೆಯ ಪ್ರೊಫೈಲ್',
    cartel_forensic_evidence: 'ಖರೀದಿ ಮತ್ತು ಹೊಂದಾಣಿಕೆಯ ಫೋರೆನ್ಸಿಕ್ ಪುರಾವೆಗಳು',
    cartel_cover_bidders: 'ಗುರುತಿಸಲಾದ ಕವರ್ / ನೆರಳು ಬಿಡ್ಡರ್‌ಗಳು',
    cartel_director_interlocking: 'ನಿರ್ದೇಶಕರ ಪರಸ್ಪರ ಸಂಪರ್ಕ ಮತ್ತು MCA ಕ್ರಾಸ್-ಹೋಲ್ಡಿಂಗ್ಸ್',
    cartel_vigilance_rec: 'ರವಾನಿಸಲಾದ ಜಾಗರೂಕತಾ ಶಿಫಾರಸು',
    cartel_btn_dossier: 'ಅಧಿಕೃತ CBI/CVC ಫೋರೆನ್ಸಿಕ್ ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    cartel_btn_freeze: 'ಖಜಾನೆ ವಿತರಣೆಯನ್ನು ಸ್ಥಗಿತಗೊಳಿಸಿ (ನಿಯಮ 239)',
    cartel_connected_works: 'ಸಂಪರ್ಕಿತ ಸಾರ್ವಜನಿಕ ಕಾಮಗಾರಿಗಳು',
    cartel_inspect_node: 'ಪರಿಶೀಲಿಸಿ',
    cartel_active_syndicate: 'ಸಕ್ರಿಯ ಸಿಂಡಿಕೇಟ್',
    cartel_critical_risk: 'ತೀವ್ರ ಅಪಾಯ',
    cartel_cover_bidding: 'ಕವರ್ ಬಿಡ್ಡಿಂಗ್',
    cartel_hhi_label: 'HHI ಸಾಂದ್ರತೆ',
    cartel_bids_won: 'ಗೆದ್ದ ಟೆಂಡರ್‌ಗಳು',
    home_statutory_view: 'ಶಾಸನಬದ್ಧ ನೋಟ',
    home_ai_vigilance: 'AI ಜಾಗರೂಕತೆ',
    home_lok_sabha: 'ಲೋಕಸಭೆ (543 ಸಂಸದರು)',
    home_rajya_sabha: 'ರಾಜ್ಯಸಭೆ (245 ಸಂಸದರು)',
    home_guidelines_title: 'ಮಾರ್ಗಸೂಚಿಗಳು ಮತ್ತು ಕಾಯಿದೆಗಳು',
    home_guidelines_sub: '2023 ಪ್ರೋಟೋಕಾಲ್',
    home_voice_title: 'ಧ್ವನಿ AI ಸಹಾಯಕ',
    home_voice_sub: '8 ಭಾರತೀಯ ಭಾಷೆಗಳು',
    home_citizen_title: 'ನಾಗರಿಕ ವಿನಂತಿ',
    home_citizen_sub: 'ಪ್ರದೇಶ ಪ್ರಸ್ತಾವನೆ',
    home_audit_title: 'AI ಆಡಿಟ್ ಕಡತ',
    home_audit_sub: 'ನಂದೂರಬಾರ್ ತಪಾಸಣೆ',
  }
};

// Merge Cartel Matrix & Extended Translations into Main DICTIONARY for all languages
Object.keys(CARTEL_DICTIONARY).forEach((langCode) => {
  if (!DICTIONARY[langCode]) DICTIONARY[langCode] = {};
  DICTIONARY[langCode] = {
    ...DICTIONARY[langCode],
    ...CARTEL_DICTIONARY[langCode],
  };
});

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('mplads_selected_lang') || 'en-IN';
  });

  useEffect(() => {
    localStorage.setItem('mplads_selected_lang', currentLanguage);
    document.documentElement.lang = currentLanguage.split('-')[0];
  }, [currentLanguage]);

  const setLanguage = (langCode) => {
    setCurrentLanguage(langCode);
  };

  const t = (key, defaultText = '') => {
    const langDict = DICTIONARY[currentLanguage] || DICTIONARY['en-IN'];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Check if defaultText itself is registered as a translation key
    if (defaultText && langDict && langDict[defaultText]) {
      return langDict[defaultText];
    }
    const enDict = DICTIONARY['en-IN'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        languages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
